import { Product } from '@/types';

export const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Vega Sicilia Unico 2019',
    description: 'Vino tinto de crianza con DO Ribera del Duero. Elaborado con Tempranillo de viñas viejas, presenta una complejidad aromática excepcional con notas de ciruela, especias y tabaco.',
    price: 89.99,
    comparePrice: 129.99,
    image: 'https://images.unsplash.com/photo-1586370434639-0fe43b2d32e6?w=400&h=600&fit=crop',
    sku: 'VS-UNICO-2019',
    stock: 12,
    featured: true,
    bodegaId: '1',
    bodega: {
      id: '1',
      name: 'Vega Sicilia',
      description: 'Bodega legendaria con más de 150 años de historia',
      country: 'España',
      region: 'Ribera del Duero',
      founded: 1864,
      image: 'https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?w=400&h=400&fit=crop',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    regionId: '1',
    region: {
      id: '1',
      name: 'Ribera del Duero',
      country: 'España',
      description: 'Una de las mejores regiones vinícolas de España',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    categoryId: '1',
    category: {
      id: '1',
      name: 'Vinos Tintos Premium',
      slug: 'vinos-tintos-premium',
      description: 'Vinos tintos de alta gama',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    grapeIds: ['1'],
    grapes: [
      {
        id: '1',
        name: 'Tempranillo',
        description: 'Uva tinta española',
        color: 'tinto',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    wineType: 'tinto',
    vintage: 2019,
    volume: 750,
    alcohol: 14.5,
    acidity: 3.8,
    ratings: [
      {
        id: '1',
        productId: '1',
        critic: 'Parker',
        score: 96,
        source: 'Robert Parker',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
  },
  {
    id: '2',
    name: 'Marqués de Murrieta Castillo Ygay 2018',
    description: 'Vino tinto crianza DO Rioja. Un tinto clásico de Rioja con envejecimiento en barrica de roble americano.',
    price: 34.99,
    comparePrice: 45.99,
    image: 'https://images.unsplash.com/photo-1586370434639-0fe43b2d32e6?w=400&h=600&fit=crop',
    sku: 'MM-2018',
    stock: 45,
    featured: true,
    bodegaId: '2',
    bodega: {
      id: '2',
      name: 'Marqués de Murrieta',
      description: 'Bodega histórica riojana fundada en 1852',
      country: 'España',
      region: 'Rioja',
      founded: 1852,
      image: 'https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?w=400&h=400&fit=crop',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    regionId: '2',
    region: {
      id: '2',
      name: 'Rioja',
      country: 'España',
      description: 'La región vitivinícola más famosa de España',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    categoryId: '1',
    category: {
      id: '1',
      name: 'Vinos Tintos',
      slug: 'vinos-tintos',
      description: 'Vinos tintos',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    grapeIds: ['1'],
    grapes: [
      {
        id: '1',
        name: 'Tempranillo',
        description: 'Uva tinta española',
        color: 'tinto',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    wineType: 'tinto',
    vintage: 2018,
    volume: 750,
    alcohol: 14,
    acidity: 3.6,
    ratings: [
      {
        id: '2',
        productId: '2',
        critic: 'Parker',
        score: 93,
        source: 'Robert Parker',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
  },
  {
    id: '3',
    name: 'Almaviva 2019',
    description: 'Vino tinto premium DO Priorat. Mezcla de Garnacha y Cariñena con crianza en barrica de roble francés.',
    price: 56.99,
    image: 'https://images.unsplash.com/photo-1586370434639-0fe43b2d32e6?w=400&h=600&fit=crop',
    sku: 'ALM-2019',
    stock: 28,
    featured: true,
    bodegaId: '3',
    bodega: {
      id: '3',
      name: 'Almaviva',
      description: 'Bodega de Priorat especializada en tintos premium',
      country: 'España',
      region: 'Priorat',
      founded: 2010,
      image: 'https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?w=400&h=400&fit=crop',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    regionId: '3',
    region: {
      id: '3',
      name: 'Priorat',
      country: 'España',
      description: 'Pequeña pero prestigiosa región de Cataluña',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    categoryId: '1',
    category: {
      id: '1',
      name: 'Vinos Tintos',
      slug: 'vinos-tintos',
      description: 'Vinos tintos',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    grapeIds: ['1', '2'],
    grapes: [
      {
        id: '1',
        name: 'Garnacha',
        description: 'Uva tinta',
        color: 'tinto',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: '2',
        name: 'Cariñena',
        description: 'Uva tinta',
        color: 'tinto',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    wineType: 'tinto',
    vintage: 2019,
    volume: 750,
    alcohol: 15,
    acidity: 3.5,
    ratings: [
      {
        id: '3',
        productId: '3',
        critic: 'Parker',
        score: 92,
        source: 'Robert Parker',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
  },
  {
    id: '4',
    name: 'Albariño Martín Códax 2023',
    description: 'Vino blanco DO Rías Baixas. Elaborado con uva Albariño, presenta aromas cítricos y minerales muy característicos.',
    price: 12.99,
    comparePrice: 16.99,
    image: 'https://images.unsplash.com/photo-1586370434639-0fe43b2d32e6?w=400&h=600&fit=crop',
    sku: 'ALB-MC-2023',
    stock: 120,
    featured: true,
    bodegaId: '4',
    bodega: {
      id: '4',
      name: 'Martín Códax',
      description: 'Bodega de Rías Baixas especializada en albariño',
      country: 'España',
      region: 'Rías Baixas',
      founded: 1986,
      image: 'https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?w=400&h=400&fit=crop',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    regionId: '4',
    region: {
      id: '4',
      name: 'Rías Baixas',
      country: 'España',
      description: 'Región de vinos blancos en Galicia',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    categoryId: '2',
    category: {
      id: '2',
      name: 'Vinos Blancos',
      slug: 'vinos-blancos',
      description: 'Vinos blancos',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    grapeIds: ['3'],
    grapes: [
      {
        id: '3',
        name: 'Albariño',
        description: 'Uva blanca gallega',
        color: 'blanco',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    wineType: 'blanco',
    vintage: 2023,
    volume: 750,
    alcohol: 12.5,
    acidity: 3.5,
    createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
  },
  {
    id: '5',
    name: 'Moët & Chandon Brut Imperial',
    description: 'Champagne francés de lujo con más de 200 años de tradición. Notas de frutas blancas y brioche.',
    price: 39.99,
    comparePrice: 52.99,
    image: 'https://images.unsplash.com/photo-1586370434639-0fe43b2d32e6?w=400&h=600&fit=crop',
    sku: 'MOET-BRUT',
    stock: 35,
    featured: true,
    bodegaId: '5',
    bodega: {
      id: '5',
      name: 'Moët & Chandon',
      description: 'Casa de champagne francesa de prestigio mundial',
      country: 'Francia',
      region: 'Champagne',
      founded: 1743,
      image: 'https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?w=400&h=400&fit=crop',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    regionId: '5',
    region: {
      id: '5',
      name: 'Champagne',
      country: 'Francia',
      description: 'Región de champagne francés',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    categoryId: '3',
    category: {
      id: '3',
      name: 'Champagne',
      slug: 'champagne',
      description: 'Champagnes',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    grapeIds: ['4', '5', '6'],
    grapes: [
      {
        id: '4',
        name: 'Chardonnay',
        description: 'Uva blanca',
        color: 'blanco',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: '5',
        name: 'Pinot Noir',
        description: 'Uva tinta',
        color: 'tinto',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: '6',
        name: 'Pinot Meunier',
        description: 'Uva tinta',
        color: 'tinto',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    wineType: 'espumoso',
    vintage: 2023,
    volume: 750,
    alcohol: 12,
    acidity: 3.2,
    ratings: [
      {
        id: '5',
        productId: '5',
        critic: 'Parker',
        score: 91,
        source: 'Robert Parker',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    createdAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
  },
  {
    id: '6',
    name: 'Cava Freixenet Cordon Negro',
    description: 'Cava español de calidad. Espumoso seco con buen equilibrio entre acidez y dulzor.',
    price: 8.99,
    comparePrice: 12.99,
    image: 'https://images.unsplash.com/photo-1586370434639-0fe43b2d32e6?w=400&h=600&fit=crop',
    sku: 'FREIX-CN',
    stock: 250,
    featured: false,
    bodegaId: '6',
    bodega: {
      id: '6',
      name: 'Freixenet',
      description: 'Bodega de cava española líder mundial',
      country: 'España',
      region: 'Penedès',
      founded: 1914,
      image: 'https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?w=400&h=400&fit=crop',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    regionId: '6',
    region: {
      id: '6',
      name: 'Penedès',
      country: 'España',
      description: 'Región de cava en Cataluña',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    categoryId: '4',
    category: {
      id: '4',
      name: 'Cava',
      slug: 'cava',
      description: 'Cavas españoles',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    grapeIds: ['4', '7', '8'],
    grapes: [
      {
        id: '4',
        name: 'Chardonnay',
        description: 'Uva blanca',
        color: 'blanco',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: '7',
        name: 'Macabeo',
        description: 'Uva blanca',
        color: 'blanco',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: '8',
        name: 'Xarel.lo',
        description: 'Uva blanca',
        color: 'blanco',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    wineType: 'espumoso',
    vintage: 2023,
    volume: 750,
    alcohol: 11.5,
    acidity: 3.3,
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
  },
  {
    id: '7',
    name: 'Domaines Ott Château de Selle Rosé 2022',
    description: 'Vino rosé premium de Provence. Elaborado con uvas Grenache, presenta un color salmón pálido excepcional.',
    price: 24.99,
    image: 'https://images.unsplash.com/photo-1586370434639-0fe43b2d32e6?w=400&h=600&fit=crop',
    sku: 'DOTT-ROSE-2022',
    stock: 60,
    featured: true,
    bodegaId: '7',
    bodega: {
      id: '7',
      name: 'Domaines Ott',
      description: 'Bodega francesa especializada en rosados de alta gama',
      country: 'Francia',
      region: 'Provence',
      founded: 1912,
      image: 'https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?w=400&h=400&fit=crop',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    regionId: '7',
    region: {
      id: '7',
      name: 'Provence',
      country: 'Francia',
      description: 'Región de rosados franceses',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    categoryId: '5',
    category: {
      id: '5',
      name: 'Vinos Rosé',
      slug: 'vinos-rose',
      description: 'Vinos rosé',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    grapeIds: ['9', '10'],
    grapes: [
      {
        id: '9',
        name: 'Grenache',
        description: 'Uva rosada',
        color: 'rosado',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: '10',
        name: 'Mourvèdre',
        description: 'Uva tinta',
        color: 'tinto',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    wineType: 'rosado',
    vintage: 2022,
    volume: 750,
    alcohol: 13,
    acidity: 3.4,
    ratings: [
      {
        id: '7',
        productId: '7',
        critic: 'Parker',
        score: 90,
        source: 'Robert Parker',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
  },
  {
    id: '8',
    name: 'Marqués de Riscal 2020 Ecológico',
    description: 'Vino tinto DO Rioja ecológico. Elaborado con métodos sostenibles y viticultura biodinámica.',
    price: 18.99,
    comparePrice: 25.99,
    image: 'https://images.unsplash.com/photo-1586370434639-0fe43b2d32e6?w=400&h=600&fit=crop',
    sku: 'MR-2020-ECO',
    stock: 80,
    featured: false,
    bodegaId: '8',
    bodega: {
      id: '8',
      name: 'Marqués de Riscal',
      description: 'Bodega histórica riojana comprometida con la sostenibilidad',
      country: 'España',
      region: 'Rioja',
      founded: 1860,
      image: 'https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?w=400&h=400&fit=crop',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    regionId: '2',
    region: {
      id: '2',
      name: 'Rioja',
      country: 'España',
      description: 'La región vitivinícola más famosa de España',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    categoryId: '1',
    category: {
      id: '1',
      name: 'Vinos Tintos',
      slug: 'vinos-tintos',
      description: 'Vinos tintos',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    grapeIds: ['1', 'organic-1'],
    grapes: [
      {
        id: '1',
        name: 'Tempranillo Organic',
        description: 'Uva tinta española ecológica',
        color: 'tinto',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    wineType: 'tinto',
    vintage: 2020,
    volume: 750,
    alcohol: 14,
    acidity: 3.5,
    createdAt: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
  },
  {
    id: '9',
    name: 'Pazo de Señoans Albariño 2022',
    description: 'Albariño premium DO Rías Baixas. Vino blanco con complejidad y mineralidad excepcional.',
    price: 16.99,
    image: 'https://images.unsplash.com/photo-1586370434639-0fe43b2d32e6?w=400&h=600&fit=crop',
    sku: 'PAZO-ALB-2022',
    stock: 95,
    featured: true,
    bodegaId: '9',
    bodega: {
      id: '9',
      name: 'Pazo de Señoans',
      description: 'Bodega gallega de albariño de gran prestigio',
      country: 'España',
      region: 'Rías Baixas',
      founded: 2001,
      image: 'https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?w=400&h=400&fit=crop',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    regionId: '4',
    region: {
      id: '4',
      name: 'Rías Baixas',
      country: 'España',
      description: 'Región de vinos blancos en Galicia',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    categoryId: '2',
    category: {
      id: '2',
      name: 'Vinos Blancos',
      slug: 'vinos-blancos',
      description: 'Vinos blancos',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    grapeIds: ['3'],
    grapes: [
      {
        id: '3',
        name: 'Albariño',
        description: 'Uva blanca gallega',
        color: 'blanco',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    wineType: 'blanco',
    vintage: 2022,
    volume: 750,
    alcohol: 12.5,
    acidity: 3.4,
    ratings: [
      {
        id: '9',
        productId: '9',
        critic: 'Parker',
        score: 89,
        source: 'Robert Parker',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
  },
  {
    id: '10',
    name: 'Vermouth Carpano Antica Formula',
    description: 'Vermut italiano premium elaborado con una mezcla secreta de hierbas y especias.',
    price: 14.99,
    comparePrice: 18.99,
    image: 'https://images.unsplash.com/photo-1586370434639-0fe43b2d32e6?w=400&h=600&fit=crop',
    sku: 'CARP-ANTIGA',
    stock: 70,
    featured: false,
    bodegaId: '10',
    bodega: {
      id: '10',
      name: 'Carpano',
      description: 'Casa italiana de vermut con 200 años de tradición',
      country: 'Italia',
      region: 'Turín',
      founded: 1786,
      image: 'https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?w=400&h=400&fit=crop',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    regionId: '8',
    region: {
      id: '8',
      name: 'Turín',
      country: 'Italia',
      description: 'Región de vermut italiano',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    categoryId: '6',
    category: {
      id: '6',
      name: 'Vermut',
      slug: 'vermut',
      description: 'Vermuts',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    grapeIds: ['11'],
    grapes: [
      {
        id: '11',
        name: 'Blend Especial',
        description: 'Blend de vermut',
        color: 'blanco',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    wineType: 'fortified',
    vintage: 2023,
    volume: 1000,
    alcohol: 16,
    acidity: 2.8,
    createdAt: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
  },
  {
    id: '11',
    name: 'La Rioja Alta Viña Ardanza 2017',
    description: 'Vino tinto reserva DO Rioja. Mezcla tradicional de Tempranillo con crianza de 24 meses en barrica.',
    price: 27.99,
    image: 'https://images.unsplash.com/photo-1586370434639-0fe43b2d32e6?w=400&h=600&fit=crop',
    sku: 'LRA-ARDANZA-2017',
    stock: 55,
    featured: true,
    bodegaId: '11',
    bodega: {
      id: '11',
      name: 'La Rioja Alta',
      description: 'Bodega tradicional riojana con métodos artesanales',
      country: 'España',
      region: 'Rioja',
      founded: 1890,
      image: 'https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?w=400&h=400&fit=crop',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    regionId: '2',
    region: {
      id: '2',
      name: 'Rioja',
      country: 'España',
      description: 'La región vitivinícola más famosa de España',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    categoryId: '1',
    category: {
      id: '1',
      name: 'Vinos Tintos',
      slug: 'vinos-tintos',
      description: 'Vinos tintos',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    grapeIds: ['1'],
    grapes: [
      {
        id: '1',
        name: 'Tempranillo',
        description: 'Uva tinta española',
        color: 'tinto',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    wineType: 'tinto',
    vintage: 2017,
    volume: 750,
    alcohol: 14.5,
    acidity: 3.6,
    ratings: [
      {
        id: '11',
        productId: '11',
        critic: 'Parker',
        score: 94,
        source: 'Robert Parker',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    createdAt: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
  },
  {
    id: '12',
    name: 'Prosecco Valdobbiadene DOCG Extra Dry',
    description: 'Prosecco italiano espumoso con finas burbujas y sabor frutal ligero.',
    price: 11.99,
    comparePrice: 15.99,
    image: 'https://images.unsplash.com/photo-1586370434639-0fe43b2d32e6?w=400&h=600&fit=crop',
    sku: 'PROSC-ED',
    stock: 150,
    featured: false,
    bodegaId: '12',
    bodega: {
      id: '12',
      name: 'Valdobbiadene',
      description: 'Bodega de prosecco italiano de gran calidad',
      country: 'Italia',
      region: 'Véneto',
      founded: 1950,
      image: 'https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?w=400&h=400&fit=crop',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    regionId: '9',
    region: {
      id: '9',
      name: 'Véneto',
      country: 'Italia',
      description: 'Región de prosecco en Italia',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    categoryId: '7',
    category: {
      id: '7',
      name: 'Prosecco',
      slug: 'prosecco',
      description: 'Proseccos italianos',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    grapeIds: ['12'],
    grapes: [
      {
        id: '12',
        name: 'Glera',
        description: 'Uva blanca italiana',
        color: 'blanco',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    wineType: 'espumoso',
    vintage: 2023,
    volume: 750,
    alcohol: 11,
    acidity: 3.2,
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
  },
  {
    id: '13',
    name: 'Riojas Alavesas Tinto Reserva 2019',
    description: 'Vino tinto DO Rioja Alavesa. Elaborado con Tempranillo de parcelas viejas, con gran complejidad.',
    price: 21.99,
    comparePrice: 29.99,
    image: 'https://images.unsplash.com/photo-1586370434639-0fe43b2d32e6?w=400&h=600&fit=crop',
    sku: 'RA-RESERVA-2019',
    stock: 75,
    featured: false,
    bodegaId: '13',
    bodega: {
      id: '13',
      name: 'Bodegas Rioja Alavesa',
      description: 'Bodega especializada en vinos de zona alavesa',
      country: 'España',
      region: 'Rioja',
      founded: 1970,
      image: 'https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?w=400&h=400&fit=crop',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    regionId: '2',
    region: {
      id: '2',
      name: 'Rioja',
      country: 'España',
      description: 'La región vitivinícola más famosa de España',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    categoryId: '1',
    category: {
      id: '1',
      name: 'Vinos Tintos',
      slug: 'vinos-tintos',
      description: 'Vinos tintos',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    grapeIds: ['1'],
    grapes: [
      {
        id: '1',
        name: 'Tempranillo',
        description: 'Uva tinta española',
        color: 'tinto',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    wineType: 'tinto',
    vintage: 2019,
    volume: 750,
    alcohol: 14,
    acidity: 3.7,
    createdAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
  },
  {
    id: '14',
    name: 'Rias Baixas Vinho Verde',
    description: 'Vino blanco ligero DO Rías Baixas con ligera carbonatación natural. Perfecto para beber frío.',
    price: 9.99,
    image: 'https://images.unsplash.com/photo-1586370434639-0fe43b2d32e6?w=400&h=600&fit=crop',
    sku: 'VERDE-LIGHT',
    stock: 200,
    featured: false,
    bodegaId: '14',
    bodega: {
      id: '14',
      name: 'Bodegas Vinho Verde',
      description: 'Bodega especializada en vinos ligeros gallegos',
      country: 'España',
      region: 'Rías Baixas',
      founded: 1995,
      image: 'https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?w=400&h=400&fit=crop',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    regionId: '4',
    region: {
      id: '4',
      name: 'Rías Baixas',
      country: 'España',
      description: 'Región de vinos blancos en Galicia',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    categoryId: '2',
    category: {
      id: '2',
      name: 'Vinos Blancos',
      slug: 'vinos-blancos',
      description: 'Vinos blancos',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    grapeIds: ['3'],
    grapes: [
      {
        id: '3',
        name: 'Albariño',
        description: 'Uva blanca gallega',
        color: 'blanco',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    wineType: 'blanco',
    vintage: 2023,
    volume: 750,
    alcohol: 11,
    acidity: 3.8,
    createdAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
  },
  {
    id: '15',
    name: 'Toro Tempranillo Joven 2022',
    description: 'Vino tinto joven DO Toro. Tinto potente y con buena estructura, sin pasar por barrica.',
    price: 13.99,
    comparePrice: 18.99,
    image: 'https://images.unsplash.com/photo-1586370434639-0fe43b2d32e6?w=400&h=600&fit=crop',
    sku: 'TORO-JOVEN-2022',
    stock: 110,
    featured: false,
    bodegaId: '15',
    bodega: {
      id: '15',
      name: 'Bodegas DO Toro',
      description: 'Bodega especializada en vinos de la denominación de origen Toro',
      country: 'España',
      region: 'Toro',
      founded: 1985,
      image: 'https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?w=400&h=400&fit=crop',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    regionId: '10',
    region: {
      id: '10',
      name: 'Toro',
      country: 'España',
      description: 'Región de vinos tintos potentes en Castilla y León',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    categoryId: '1',
    category: {
      id: '1',
      name: 'Vinos Tintos',
      slug: 'vinos-tintos',
      description: 'Vinos tintos',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    grapeIds: ['1'],
    grapes: [
      {
        id: '1',
        name: 'Tempranillo',
        description: 'Uva tinta española',
        color: 'tinto',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    wineType: 'tinto',
    vintage: 2022,
    volume: 750,
    alcohol: 14.5,
    acidity: 3.5,
    createdAt: new Date(Date.now() - 50 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
  },
  {
    id: '16',
    name: 'Penedès Cabernet Sauvignon 2021',
    description: 'Vino tinto DO Penedès elaborado con Cabernet Sauvignon de viñas centenarias.',
    price: 19.99,
    image: 'https://images.unsplash.com/photo-1586370434639-0fe43b2d32e6?w=400&h=600&fit=crop',
    sku: 'PEN-CAB-2021',
    stock: 85,
    featured: false,
    bodegaId: '16',
    bodega: {
      id: '16',
      name: 'Bodegas Penedès Cabernet',
      description: 'Bodega tradicional catalana',
      country: 'España',
      region: 'Penedès',
      founded: 1975,
      image: 'https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?w=400&h=400&fit=crop',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    regionId: '6',
    region: {
      id: '6',
      name: 'Penedès',
      country: 'España',
      description: 'Región de cava en Cataluña',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    categoryId: '1',
    category: {
      id: '1',
      name: 'Vinos Tintos',
      slug: 'vinos-tintos',
      description: 'Vinos tintos',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    grapeIds: ['13'],
    grapes: [
      {
        id: '13',
        name: 'Cabernet Sauvignon',
        description: 'Uva tinta francesa',
        color: 'tinto',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    wineType: 'tinto',
    vintage: 2021,
    volume: 750,
    alcohol: 13.5,
    acidity: 3.6,
    createdAt: new Date(Date.now() - 35 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
  },
  {
    id: '17',
    name: 'Rosé Provence Premium 2023',
    description: 'Rosé de Provence de alta gama. Delicado y elegante con notas florales.',
    price: 22.99,
    comparePrice: 31.99,
    image: 'https://images.unsplash.com/photo-1586370434639-0fe43b2d32e6?w=400&h=600&fit=crop',
    sku: 'ROSE-PROV-2023',
    stock: 65,
    featured: true,
    bodegaId: '17',
    bodega: {
      id: '17',
      name: 'Domaine Provence Rosé',
      description: 'Bodega francesa especializada en rosados premium',
      country: 'Francia',
      region: 'Provence',
      founded: 1920,
      image: 'https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?w=400&h=400&fit=crop',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    regionId: '7',
    region: {
      id: '7',
      name: 'Provence',
      country: 'Francia',
      description: 'Región de rosados franceses',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    categoryId: '5',
    category: {
      id: '5',
      name: 'Vinos Rosé',
      slug: 'vinos-rose',
      description: 'Vinos rosé',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    grapeIds: ['9'],
    grapes: [
      {
        id: '9',
        name: 'Grenache',
        description: 'Uva rosada',
        color: 'rosado',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    wineType: 'rosado',
    vintage: 2023,
    volume: 750,
    alcohol: 12.5,
    acidity: 3.5,
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
  },
  {
    id: '18',
    name: 'Champagne Veuve Clicquot Yellow Label',
    description: 'Champagne clásico francés con gran presencia en paladar. Notas de frutas blancas y brioche.',
    price: 49.99,
    comparePrice: 65.99,
    image: 'https://images.unsplash.com/photo-1586370434639-0fe43b2d32e6?w=400&h=600&fit=crop',
    sku: 'VC-YELLOW',
    stock: 25,
    featured: true,
    bodegaId: '18',
    bodega: {
      id: '18',
      name: 'Veuve Clicquot',
      description: 'Casa de champagne francesa de máxima prestigio',
      country: 'Francia',
      region: 'Champagne',
      founded: 1772,
      image: 'https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?w=400&h=400&fit=crop',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    regionId: '5',
    region: {
      id: '5',
      name: 'Champagne',
      country: 'Francia',
      description: 'Región de champagne francés',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    categoryId: '3',
    category: {
      id: '3',
      name: 'Champagne',
      slug: 'champagne',
      description: 'Champagnes',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    grapeIds: ['4', '5'],
    grapes: [
      {
        id: '4',
        name: 'Chardonnay',
        description: 'Uva blanca',
        color: 'blanco',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: '5',
        name: 'Pinot Noir',
        description: 'Uva tinta',
        color: 'tinto',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    wineType: 'espumoso',
    vintage: 2022,
    volume: 750,
    alcohol: 12,
    acidity: 3.2,
    ratings: [
      {
        id: '18',
        productId: '18',
        critic: 'Parker',
        score: 95,
        source: 'Robert Parker',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    createdAt: new Date(Date.now() - 40 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
  },
  {
    id: '19',
    name: 'Txakoli Blanco Getariako 2023',
    description: 'Vino blanco DOP Getariako Txakolina. Vino ligero con burbujitas naturales, típico de Euskadi.',
    price: 10.99,
    image: 'https://images.unsplash.com/photo-1586370434639-0fe43b2d32e6?w=400&h=600&fit=crop',
    sku: 'TXAK-2023',
    stock: 90,
    featured: false,
    bodegaId: '19',
    bodega: {
      id: '19',
      name: 'Bodegas Txakoli Getaria',
      description: 'Bodega vasca de txakoli traditional',
      country: 'España',
      region: 'Getaria',
      founded: 1985,
      image: 'https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?w=400&h=400&fit=crop',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    regionId: '11',
    region: {
      id: '11',
      name: 'Getaria',
      country: 'España',
      description: 'Región de txakoli en el País Vasco',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    categoryId: '2',
    category: {
      id: '2',
      name: 'Vinos Blancos',
      slug: 'vinos-blancos',
      description: 'Vinos blancos',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    grapeIds: ['14'],
    grapes: [
      {
        id: '14',
        name: 'Hondarribi Zuri',
        description: 'Uva blanca vasca',
        color: 'blanco',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    wineType: 'blanco',
    vintage: 2023,
    volume: 750,
    alcohol: 11,
    acidity: 3.9,
    createdAt: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
  },
  {
    id: '20',
    name: 'Jerez Fino La Ina 2021',
    description: 'Jerez Fino de la región de Jerez. Vino generoso seco con gran carácter y tradición.',
    price: 15.99,
    comparePrice: 21.99,
    image: 'https://images.unsplash.com/photo-1586370434639-0fe43b2d32e6?w=400&h=600&fit=crop',
    sku: 'JEREZ-FINO',
    stock: 100,
    featured: false,
    bodegaId: '20',
    bodega: {
      id: '20',
      name: 'Bodegas Diez Mérito',
      description: 'Bodega jerezana con 150 años de tradición',
      country: 'España',
      region: 'Jerez',
      founded: 1870,
      image: 'https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?w=400&h=400&fit=crop',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    regionId: '12',
    region: {
      id: '12',
      name: 'Jerez',
      country: 'España',
      description: 'Región de vinos generosos en Andalucía',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    categoryId: '8',
    category: {
      id: '8',
      name: 'Jerez',
      slug: 'jerez',
      description: 'Vinos de Jerez',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    grapeIds: ['15'],
    grapes: [
      {
        id: '15',
        name: 'Palomino',
        description: 'Uva blanca de Jerez',
        color: 'blanco',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    wineType: 'fortified',
    vintage: 2021,
    volume: 750,
    alcohol: 15.5,
    acidity: 3.2,
    createdAt: new Date(Date.now() - 55 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
  },
];

export const MOCK_FILTERS = {
  wineTypes: {
    tinto: 45,
    blanco: 38,
    rosado: 12,
    espumoso: 25,
    fortified: 8,
  },
  regions: {
    rioja: 45,
    ribera: 38,
    penedes: 32,
    priorat: 18,
    riojas_alavesas: 22,
    rasas_baixas: 28,
    toro: 15,
    jerez: 10,
  },
  priceRanges: {
    '0-20': 85,
    '20-50': 62,
    '50-100': 28,
    '100+': 12,
  },
};
