import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

async function main() {
  console.log('Starting seed...')

  // Clear existing data
  await prisma.packProduct.deleteMany()
  await prisma.pack.deleteMany()
  await prisma.discountCode.deleteMany()
  await prisma.stockAlert.deleteMany()
  await prisma.wishlistItem.deleteMany()
  await prisma.review.deleteMany()
  await prisma.rating.deleteMany()
  await prisma.orderItem.deleteMany()
  await prisma.order.deleteMany()
  await prisma.cartItem.deleteMany()
  await prisma.productCategory.deleteMany()
  await prisma.productGrape.deleteMany()
  await prisma.product.deleteMany()
  await prisma.category.deleteMany()
  await prisma.grape.deleteMany()
  await prisma.bodega.deleteMany()
  await prisma.region.deleteMany()
  await prisma.blogPost.deleteMany()
  await prisma.address.deleteMany()
  await prisma.session.deleteMany()
  await prisma.account.deleteMany()
  await prisma.user.deleteMany()

  // Create Bodegas
  const bodegas = await Promise.all([
    prisma.bodega.create({
      data: {
        name: 'Vega Sicilia',
        slug: 'vega-sicilia',
        country: 'España',
        regions: ['Ribera del Duero'],
        oenologist: 'Pablo Álvarez García',
        description: 'Legendaria bodega fundada en 1864, productora de algunos de los mejores vinos de España. Pionera en la introducción de variedades internacionales en la región.',
        image: '/bodegas/vega-sicilia.jpg',
      },
    }),
    prisma.bodega.create({
      data: {
        name: 'Bodegas Pingus',
        slug: 'bodegas-pingus',
        country: 'España',
        regions: ['Ribera del Duero'],
        oenologist: 'Peter Sisseck',
        description: 'Pequeña bodega artesanal fundada en 1995 por el enólogo danés Peter Sisseck. Produce vinos de culto reconocidos internacionalmente.',
        image: '/bodegas/pingus.jpg',
      },
    }),
    prisma.bodega.create({
      data: {
        name: 'Marqués de Riscal',
        slug: 'marques-de-riscal',
        country: 'España',
        regions: ['Rioja'],
        oenologist: 'Ignacio Urarte',
        description: 'Una de las bodegas más antiguas de Rioja, fundada en 1858. Combina tradición e innovación en la producción de vinos de clase mundial.',
        image: '/bodegas/marques-riscal.jpg',
      },
    }),
    prisma.bodega.create({
      data: {
        name: 'Torres',
        slug: 'torres',
        country: 'España',
        regions: ['Penedès', 'Riojas Altas', 'Tarragona'],
        oenologist: 'Miguel A. Torres',
        description: 'Bodega familiar con más de 300 años de historia en Cataluña. Reconocida por su compromiso con la sostenibilidad y la innovación.',
        image: '/bodegas/torres.jpg',
      },
    }),
    prisma.bodega.create({
      data: {
        name: 'Álvaro Palacios',
        slug: 'alvaro-palacios',
        country: 'España',
        regions: ['Priorat', 'Bierzo'],
        oenologist: 'Álvaro Palacios',
        description: 'Bodega boutique especializada en vinos de pequeña producción con expresión terroir. Pionera en la elaboración de vinos naturales en Priorat.',
        image: '/bodegas/alvaro-palacios.jpg',
      },
    }),
    prisma.bodega.create({
      data: {
        name: 'Bodegas Muga',
        slug: 'bodegas-muga',
        country: 'España',
        regions: ['Rioja'],
        oenologist: 'Isaac Fernández Soria',
        description: 'Bodega centenaria en Haro, Rioja Alta. Conocida por métodos tradicionales de vinificación y crianza en barrica.',
        image: '/bodegas/muga.jpg',
      },
    }),
    prisma.bodega.create({
      data: {
        name: 'Telmo Rodríguez',
        slug: 'telmo-rodriguez',
        country: 'España',
        regions: ['Soria', 'Castilla la Mancha', 'Jerez'],
        oenologist: 'Telmo Rodríguez',
        description: 'Proyecto del reconocido enólogo Telmo Rodríguez. Rescata viñas antiguas y tradicionales produciendo vinos de gran complejidad.',
        image: '/bodegas/telmo-rodriguez.jpg',
      },
    }),
    prisma.bodega.create({
      data: {
        name: 'Raúl Pérez',
        slug: 'raul-perez',
        country: 'España',
        regions: ['Bierzo'],
        oenologist: 'Raúl Pérez García',
        description: 'Productor visionario en el Bierzo. Sus vinos naturales de Mencía han ganado reconocimiento internacional por su autenticidad.',
        image: '/bodegas/raul-perez.jpg',
      },
    }),
    prisma.bodega.create({
      data: {
        name: 'López de Heredia',
        slug: 'lopez-heredia',
        country: 'España',
        regions: ['Rioja'],
        oenologist: 'María José López de Heredia',
        description: 'Tradición desde 1877. Bodega de Rioja Alta conocida por sus largos períodos de crianza y vinos de gran longevidad.',
        image: '/bodegas/lopez-heredia.jpg',
      },
    }),
    prisma.bodega.create({
      data: {
        name: 'Château Margaux',
        slug: 'chateau-margaux',
        country: 'Francia',
        regions: ['Burdeos'],
        oenologist: 'Paul Pontallier',
        description: 'Uno de los grandes clasificados de Burdeos. Produce Cabernet Sauvignon de excepcional elegancia y guarda para largas décadas.',
        image: '/bodegas/chateau-margaux.jpg',
      },
    }),
  ])

  // Create Regions
  const regions = await Promise.all([
    prisma.region.create({
      data: {
        name: 'Ribera del Duero',
        slug: 'ribera-del-duero',
        country: 'España',
        description: 'Región vitivinícola de Castilla y León famosa por sus vinos tintos de Tempranillo. Viñas a gran altitud con terroir único.',
        image: '/regions/ribera-duero.jpg',
      },
    }),
    prisma.region.create({
      data: {
        name: 'Rioja',
        slug: 'rioja',
        country: 'España',
        description: 'La región vitivinícola más prestigiosa de España. Tradición de siglos en la elaboración de vinos elegantes y estructurados.',
        image: '/regions/rioja.jpg',
      },
    }),
    prisma.region.create({
      data: {
        name: 'Priorat',
        slug: 'priorat',
        country: 'España',
        description: 'Pequeña región en Tarragona con viñas en pendientes empinadas. Vinos potentes y concentrados de gran expresión terroir.',
        image: '/regions/priorat.jpg',
      },
    }),
    prisma.region.create({
      data: {
        name: 'Bierzo',
        slug: 'bierzo',
        country: 'España',
        description: 'Región emergente en León. Especializada en Mencía, produce vinos frescos con gran personalidad y carácter mineral.',
        image: '/regions/bierzo.jpg',
      },
    }),
    prisma.region.create({
      data: {
        name: 'Rías Baixas',
        slug: 'rias-baixas',
        country: 'España',
        description: 'Región costera de Galicia especializada en vinos blancos. Albariño de gran frescura y salinidad, ideales para mariscos.',
        image: '/regions/rias-baixas.jpg',
      },
    }),
    prisma.region.create({
      data: {
        name: 'Penedès',
        slug: 'penedes',
        country: 'España',
        description: 'Región vitivinícola de Cataluña con tradición de espumosos y vinos secos. Variedad de microclimas y altitudes.',
        image: '/regions/penedes.jpg',
      },
    }),
    prisma.region.create({
      data: {
        name: 'Champagne',
        slug: 'champagne',
        country: 'Francia',
        description: 'La región de los espumosos de renombre mundial. Tiza del subsuelo produce vinos con gran finura y acidez.',
        image: '/regions/champagne.jpg',
      },
    }),
    prisma.region.create({
      data: {
        name: 'Burdeos',
        slug: 'burdeos',
        country: 'Francia',
        description: 'La región vitivinícola más prestigiosa de Francia. Produce Cabernet Sauvignon y Merlot de excepcional calidad.',
        image: '/regions/burdeos.jpg',
      },
    }),
  ])

  // Create Grapes
  const grapes = await Promise.all([
    prisma.grape.create({ data: { name: 'Tempranillo', slug: 'tempranillo' } }),
    prisma.grape.create({ data: { name: 'Garnacha', slug: 'garnacha' } }),
    prisma.grape.create({ data: { name: 'Monastrell', slug: 'monastrell' } }),
    prisma.grape.create({ data: { name: 'Mencía', slug: 'mencia' } }),
    prisma.grape.create({ data: { name: 'Albariño', slug: 'albarino' } }),
    prisma.grape.create({ data: { name: 'Verdejo', slug: 'verdejo' } }),
    prisma.grape.create({ data: { name: 'Godello', slug: 'godello' } }),
    prisma.grape.create({ data: { name: 'Viura', slug: 'viura' } }),
    prisma.grape.create({ data: { name: 'Cabernet Sauvignon', slug: 'cabernet-sauvignon' } }),
    prisma.grape.create({ data: { name: 'Merlot', slug: 'merlot' } }),
    prisma.grape.create({ data: { name: 'Pinot Noir', slug: 'pinot-noir' } }),
    prisma.grape.create({ data: { name: 'Chardonnay', slug: 'chardonnay' } }),
    prisma.grape.create({ data: { name: 'Sauvignon Blanc', slug: 'sauvignon-blanc' } }),
    prisma.grape.create({ data: { name: 'Syrah', slug: 'syrah' } }),
    prisma.grape.create({ data: { name: 'Macabeo', slug: 'macabeo' } }),
    prisma.grape.create({ data: { name: 'Xarel·lo', slug: 'xarello' } }),
    prisma.grape.create({ data: { name: 'Parellada', slug: 'parellada' } }),
    prisma.grape.create({ data: { name: 'Palomino', slug: 'palomino' } }),
    prisma.grape.create({ data: { name: 'Pedro Ximénez', slug: 'pedro-ximenez' } }),
    prisma.grape.create({ data: { name: 'Bobal', slug: 'bobal' } }),
  ])

  // Create Categories
  const categories = await Promise.all([
    prisma.category.create({
      data: {
        name: 'Vinos',
        slug: 'vinos',
        type: 'parent',
      },
    }),
    prisma.category.create({
      data: {
        name: 'Espumosos',
        slug: 'espumosos',
        type: 'parent',
      },
    }),
    prisma.category.create({
      data: {
        name: 'Destilados',
        slug: 'destilados',
        type: 'parent',
      },
    }),
    prisma.category.create({
      data: {
        name: 'Ofertas',
        slug: 'ofertas',
        type: 'parent',
      },
    }),
    prisma.category.create({
      data: {
        name: 'Selecciones',
        slug: 'selecciones',
        type: 'parent',
      },
    }),
  ])

  // Create subcategories
  const subCategories = await Promise.all([
    prisma.category.create({
      data: {
        name: 'Tintos',
        slug: 'tintos',
        type: 'child',
        parentId: categories[0].id,
      },
    }),
    prisma.category.create({
      data: {
        name: 'Blancos',
        slug: 'blancos',
        type: 'child',
        parentId: categories[0].id,
      },
    }),
    prisma.category.create({
      data: {
        name: 'Rosados',
        slug: 'rosados',
        type: 'child',
        parentId: categories[0].id,
      },
    }),
    prisma.category.create({
      data: {
        name: 'Cava',
        slug: 'cava',
        type: 'child',
        parentId: categories[1].id,
      },
    }),
    prisma.category.create({
      data: {
        name: 'Champagne',
        slug: 'champagne',
        type: 'child',
        parentId: categories[1].id,
      },
    }),
  ])

  // Create Products
  const products = await Promise.all([
    // Tintos Ribera del Duero
    prisma.product.create({
      data: {
        name: 'Pingus 2019',
        slug: 'pingus-2019',
        tagline: 'Tempranillo de culto',
        description:
          'Vino legendario producido en pequeña cantidad por Peter Sisseck. Envejecimiento en barrica nueva durante 16 meses. Expresión pura del terroir de Ribera del Duero con notas de frutas negras maduras, especias y minerales.',
        shortDescription: 'Tempranillo de pequeña producción, muy buscado por coleccionistas',
        type: 'tinto',
        price: 295.0,
        comparePrice: 350.0,
        stock: 12,
        isRecommended: true,
        isFeatured: true,
        alcoholDegree: 14.5,
        production: 'Ribera del Duero',
        temperature: '18°C',
        servingNote: 'Descorchar 30 minutos antes de servir',
        fermentation: 'Levaduras silvestres',
        aging: '16 meses en barrica nueva',
        wood: 'Roble francés 100%',
        vineyardName: 'Viña Pingus',
        vineyardSoil: 'Arcilla y tiza',
        vineyardClimate: 'Continental extremo',
        vineyardAltitude: '850 m',
        bodyLevel: 5,
        tanninLevel: 5,
        sweetnessLevel: 1,
        acidityLevel: 3,
        sight: 'Granate oscuro intenso con reflejos púrpura',
        nose: 'Frutas negras, ciruela, café, tabaco, especias oscuras',
        mouth: 'Potente y estructurado, tánicos maduros y envolventes, final largo y persistente',
        pairing: 'Carnes rojas a la parrilla, cazuelas de carne, quesos curados',
        image: '/products/pingus-2019.jpg',
        format: '0,75L',
        vintage: '2019',
        availableVintages: ['2019', '2018', '2017'],
        availableFormats: ['0,75L'],
        bodegaId: bodegas[1].id,
        regionId: regions[0].id,
      },
    }),
    prisma.product.create({
      data: {
        name: 'Vega Sicilia Unico 2018',
        slug: 'vega-sicilia-unico-2018',
        tagline: 'Tinto reserva de referencia',
        description:
          'Legendario vino español de envejecimiento excepcional. Mezcla de Tempranillo, Cabernet Sauvignon y Merlot envejecido en roble durante 8 años antes de comercialización. Ricos aromas a frutas maduras, licor, chocolate y vainilla.',
        shortDescription: 'Vino de guarda con legado de más de 150 años',
        type: 'tinto',
        price: 185.5,
        comparePrice: 220.0,
        stock: 25,
        isRecommended: true,
        alcoholDegree: 14.0,
        production: 'Ribera del Duero',
        temperature: '18°C',
        servingNote: 'Decanta 1 hora antes de servir',
        fermentation: 'Levaduras seleccionadas',
        aging: '8 años en roble francés y americano',
        wood: 'Roble francés y americano',
        vineyardName: 'Viñas de Vega Sicilia',
        vineyardSoil: 'Arcillas calizas',
        vineyardClimate: 'Continental',
        vineyardAltitude: '750-850 m',
        bodyLevel: 4,
        tanninLevel: 4,
        sweetnessLevel: 1,
        acidityLevel: 3,
        sight: 'Rojo granate intenso, cristalino',
        nose: 'Frutas rojas y negras maduras, cuero, tabaco, vainilla',
        mouth: 'Elegante y complejo, excelente equilibrio, final de gran persistencia',
        pairing: 'Asados, civet, quesos semicurados, embutidos ibéricos',
        image: '/products/vega-sicilia-2018.jpg',
        format: '0,75L',
        vintage: '2018',
        availableVintages: ['2018', '2016', '2014'],
        availableFormats: ['0,75L'],
        bodegaId: bodegas[0].id,
        regionId: regions[0].id,
      },
    }),
    prisma.product.create({
      data: {
        name: 'Ribera del Duero DO Crianza 2021',
        slug: 'ribera-duero-crianza-2021',
        tagline: 'Tinto clásico de Ribera',
        description:
          'Vino tinto joven de carácter marcado. Envejecido en roble durante 12 meses. Notas de cerezas, frambuesas y especias dulces. Estructura equilibrada con buenos tánicos.',
        shortDescription: 'Excelente relación calidad-precio de la región',
        type: 'tinto',
        price: 24.99,
        comparePrice: 32.0,
        stock: 150,
        isNew: true,
        alcoholDegree: 13.5,
        production: 'Ribiera del Duero',
        temperature: '17°C',
        servingNote: 'Servir a temperatura ambiente',
        aging: '12 meses en roble francés',
        bodyLevel: 3,
        tanninLevel: 3,
        sweetnessLevel: 1,
        acidityLevel: 3,
        sight: 'Rojo cereza profundo',
        nose: 'Cerezas, frambuesas, canela, notas de roble',
        mouth: 'Afrutado, tánicos sedosos, final agradable',
        pairing: 'Carnes rojas, pasta a la bolognesa, quesos tiernos',
        image: '/products/ribera-duero-crianza.jpg',
        format: '0,75L',
        vintage: '2021',
        availableVintages: ['2021', '2020'],
        availableFormats: ['0,75L'],
        bodegaId: bodegas[0].id,
        regionId: regions[0].id,
      },
    }),
    // Tintos Rioja
    prisma.product.create({
      data: {
        name: 'Marqués de Riscal Reserva 2017',
        slug: 'marques-de-riscal-reserva-2017',
        tagline: 'Rioja Reserva de gran elegancia',
        description:
          'Vino de tradición centenaria. Cuidada selección de Tempranillo. Envejecimiento en roble durante 24 meses seguido de tiempos en botella. Expresión clásica del vino de Rioja con gran estructura y potencial de guarda.',
        shortDescription: 'Símbolo del Rioja de calidad desde 1858',
        type: 'tinto',
        price: 64.5,
        comparePrice: 78.0,
        stock: 60,
        isRecommended: true,
        alcoholDegree: 13.5,
        production: 'Rioja',
        temperature: '18°C',
        servingNote: 'Descorchar 45 minutos antes de consumir',
        fermentation: 'Levaduras seleccionadas',
        aging: '24 meses en barrica de roble francés',
        wood: 'Roble francés y americano',
        vineyardName: 'Viñedos del Marqués',
        vineyardSoil: 'Arcillas calcáreas',
        vineyardClimate: 'Mediterráneo continentalizado',
        vineyardAltitude: '450-550 m',
        bodyLevel: 4,
        tanninLevel: 4,
        sweetnessLevel: 1,
        acidityLevel: 3,
        sight: 'Rojo granate con matices teja',
        nose: 'Frutas negras, cuero, tamarisco, vainilla',
        mouth: 'Equilibrado, tánicos nobles, evoluciona en boca',
        pairing: 'Carnes rojas, cordero asado, quesos semicurados, jamón ibérico',
        image: '/products/marques-riscal-reserva.jpg',
        format: '0,75L',
        vintage: '2017',
        availableVintages: ['2017', '2015', '2013'],
        availableFormats: ['0,75L'],
        bodegaId: bodegas[2].id,
        regionId: regions[1].id,
      },
    }),
    prisma.product.create({
      data: {
        name: 'Bodegas Muga Reserva 2019',
        slug: 'muga-reserva-2019',
        tagline: 'Rioja Reserva tradicional',
        description:
          'Elaborado según métodos ancestrales. Tempranillo puro envejecido en barrica de roble. Notas de frutas rojas maduras, especias y madera bien integrada. Excelente para los próximos 10 años.',
        shortDescription: 'Tradición centenaria en Rioja Alta',
        type: 'tinto',
        price: 32.75,
        comparePrice: 42.0,
        stock: 85,
        alcoholDegree: 13.5,
        production: 'Rioja Alta',
        temperature: '17°C',
        aging: '24 meses en roble francés',
        bodyLevel: 3,
        tanninLevel: 3,
        sweetnessLevel: 1,
        acidityLevel: 3,
        sight: 'Rojo rubí profundo con tintes teja',
        nose: 'Frutas rojas, especias, vainilla sutil',
        mouth: 'Elegante, tánicos redondos, buena persistencia',
        pairing: 'Carne a la brasa, caza menor, quesos curados',
        image: '/products/muga-reserva.jpg',
        format: '0,75L',
        vintage: '2019',
        availableVintages: ['2019', '2018'],
        availableFormats: ['0,75L'],
        bodegaId: bodegas[5].id,
        regionId: regions[1].id,
      },
    }),
    prisma.product.create({
      data: {
        name: 'López de Heredia Viña Tondonia Reserva 2015',
        slug: 'lopez-heredia-tondonia-2015',
        tagline: 'Rioja clásico de larga guarda',
        description:
          'Joya del Rioja antiguo. Envejecido 10 años en barrica antes de su comercialización. Aromas terciarios complejos con evolución constante. Expresión pura de la tradición rioiana.',
        shortDescription: 'Longevidad excepcional para coleccionistas',
        type: 'tinto',
        price: 78.0,
        comparePrice: 95.0,
        stock: 40,
        isRecommended: true,
        alcoholDegree: 12.5,
        production: 'Rioja Alta',
        temperature: '17°C',
        aging: '10 años en barrica, posterior tiempos en botella',
        wood: 'Roble francés tradicional',
        bodyLevel: 3,
        tanninLevel: 2,
        sweetnessLevel: 1,
        acidityLevel: 3,
        sight: 'Rojo teja brillante, cristalino',
        nose: 'Evolucionado, compota, cuero, tabaco, minerales',
        mouth: 'Sedoso, elegante, final extraordinariamente largo',
        pairing: 'Carnes blancas suavemente adobadas, quesos blandos, caza',
        image: '/products/lopez-heredia-2015.jpg',
        format: '0,75L',
        vintage: '2015',
        availableVintages: ['2015'],
        availableFormats: ['0,75L'],
        bodegaId: bodegas[8].id,
        regionId: regions[1].id,
      },
    }),
    // Tintos Priorat y Bierzo
    prisma.product.create({
      data: {
        name: 'Priorat DOQ Roble 2021',
        slug: 'priorat-doq-roble-2021',
        tagline: 'Garnacha potente de Priorat',
        description:
          'Vino de expresión terruño. Garnacha de viñas antiguas en terrenos escarpados de pizarra. Aromas intensos de frutas negras desecadas, especias oscuras y minerales. Estructura potente y tánica.',
        shortDescription: 'Concentración extrema del Priorat',
        type: 'tinto',
        price: 42.5,
        comparePrice: 55.0,
        stock: 45,
        isNew: true,
        alcoholDegree: 14.5,
        production: 'Priorat',
        temperature: '18°C',
        aging: '12 meses en roble',
        bodyLevel: 5,
        tanninLevel: 4,
        sweetnessLevel: 1,
        acidityLevel: 3,
        sight: 'Rojo profundo casi negro',
        nose: 'Frutas negras secas, graphito, especias oscuras',
        mouth: 'Potente y concentrado, tánicos robustos',
        pairing: 'Carnes asadas, cordero, caza mayor, quesos muy curados',
        image: '/products/priorat-roble.jpg',
        format: '0,75L',
        vintage: '2021',
        availableVintages: ['2021', '2020'],
        availableFormats: ['0,75L'],
        bodegaId: bodegas[4].id,
        regionId: regions[2].id,
      },
    }),
    prisma.product.create({
      data: {
        name: 'Raúl Pérez Mencia Bierzo 2022',
        slug: 'raul-perez-mencia-2022',
        tagline: 'Mencía natural del Bierzo',
        description:
          'Producción artesanal de Mencía con métodos naturales. Viñas viejas en terrenos de pizarra y arcilla. Aromas frescos de frutas rojas, especias y minerales. Vino dinámico con personalidad propia.',
        shortDescription: 'Puro Bierzo en su máxima expresión',
        type: 'tinto',
        price: 35.99,
        comparePrice: 45.0,
        stock: 55,
        isNew: true,
        alcoholDegree: 13.5,
        production: 'Bierzo',
        temperature: '16°C',
        aging: 'Fermentación natural, tiempos en depósito',
        filtration: 'Sin filtrar',
        bodyLevel: 3,
        tanninLevel: 3,
        sweetnessLevel: 1,
        acidityLevel: 4,
        sight: 'Rojo rubí con tonalidades púrpura',
        nose: 'Frutas rojas frescas, pimienta negra, minerales',
        mouth: 'Fresco y vibrante, estructura mineral, taninos discretos',
        pairing: 'Quesos de oveja, embutidos curados, pescados azules, legumbres',
        image: '/products/raul-perez-mencia.jpg',
        format: '0,75L',
        vintage: '2022',
        availableVintages: ['2022', '2021'],
        availableFormats: ['0,75L'],
        bodegaId: bodegas[7].id,
        regionId: regions[3].id,
      },
    }),
    // Blancos
    prisma.product.create({
      data: {
        name: 'Albariño Rías Baixas 2023',
        slug: 'albarino-rias-baixas-2023',
        tagline: 'Blanco fresco de Galicia',
        description:
          'Vino blanco icónico de Galicia. Albariño de frescura mineral y salinidad cautivadora. Aromas de frutas blancas, flores y notas de yodo. Ideal para mariscos y pescados frescos.',
        shortDescription: 'Blanco gourmet para pescados y mariscos',
        type: 'blanco',
        price: 18.5,
        comparePrice: 24.0,
        stock: 120,
        isRecommended: true,
        alcoholDegree: 12.5,
        production: 'Rías Baixas',
        temperature: '8-10°C',
        servingNote: 'Bien frío, entre 8 y 10 grados',
        aging: 'Sin envejecimiento',
        bodyLevel: 2,
        tanninLevel: 0,
        sweetnessLevel: 1,
        acidityLevel: 4,
        sight: 'Amarillo pálido con reflejos verdosos',
        nose: 'Frutas blancas frescas, flores, mineralidad salina',
        mouth: 'Fresco y vivaz, salivante, final persistente',
        pairing: 'Mariscos a la gallega, pulpo a la feira, percebes, langostinos, ostras',
        image: '/products/albarino-rias-baixas.jpg',
        format: '0,75L',
        vintage: '2023',
        availableVintages: ['2023', '2022'],
        availableFormats: ['0,75L'],
        bodegaId: bodegas[0].id,
        regionId: regions[4].id,
      },
    }),
    prisma.product.create({
      data: {
        name: 'Verdejo Rueda 2023',
        slug: 'verdejo-rueda-2023',
        tagline: 'Blanco mineral de Castilla',
        description:
          'Verdejo puro de la región de Rueda. Fermentación controlada en acero inoxidable para preservar aromas varietales. Fresco y mineral con notas herbáceas y cítricas.',
        shortDescription: 'Blanco español de gran acidez natural',
        type: 'blanco',
        price: 16.75,
        comparePrice: 21.0,
        stock: 100,
        alcoholDegree: 12.5,
        production: 'Rueda',
        temperature: '8-10°C',
        aging: 'Sin envejecimiento, fermentación en acero',
        bodyLevel: 2,
        tanninLevel: 0,
        sweetnessLevel: 1,
        acidityLevel: 4,
        sight: 'Amarillo verdoso cristalino',
        nose: 'Hinojo, tomillo, manzana verde, cítricos',
        mouth: 'Muy fresco, mineral, acidez vivificante',
        pairing: 'Espárragos, alcachofas, quesos frescos, pescados delicados',
        image: '/products/verdejo-rueda.jpg',
        format: '0,75L',
        vintage: '2023',
        availableVintages: ['2023', '2022'],
        availableFormats: ['0,75L'],
        bodegaId: bodegas[6].id,
        regionId: regions[4].id,
      },
    }),
    prisma.product.create({
      data: {
        name: 'Godello Valdeorras 2022',
        slug: 'godello-valdeorras-2022',
        tagline: 'Blanco mineral de Galicia',
        description:
          'Godello blanco de gran potencial. Viñas en terrenos de pizarra confieren mineralidad única. Aromas complejos de frutas blancas, flores secas y notas herbáceas.',
        shortDescription: 'Varidad autóctona gallega recuperada',
        type: 'blanco',
        price: 22.0,
        comparePrice: 28.0,
        stock: 70,
        alcoholDegree: 12.0,
        production: 'Valdeorras',
        temperature: '9-11°C',
        aging: 'Crianza en acero inoxidable',
        bodyLevel: 3,
        tanninLevel: 0,
        sweetnessLevel: 1,
        acidityLevel: 3,
        sight: 'Amarillo dorado pálido',
        nose: 'Pera, manzana blanca, anís, minerales',
        mouth: 'Complejo, mineralidad notable, acidez equilibrada',
        pairing: 'Jamón ibérico, queso de cabra, pescados con salsas suaves',
        image: '/products/godello-valdeorras.jpg',
        format: '0,75L',
        vintage: '2022',
        availableVintages: ['2022', '2021'],
        availableFormats: ['0,75L'],
        bodegaId: bodegas[6].id,
        regionId: regions[4].id,
      },
    }),
    prisma.product.create({
      data: {
        name: 'Viura Marqués de Murrieta 2021',
        slug: 'viura-murrieta-2021',
        tagline: 'Blanco crianza de Rioja',
        description:
          'Viura envejecido en barrica durante 6 meses. Blanco con cuerpo y complejidad. Notas de frutas blancas maduras, vainilla sutil y mineralidad.',
        shortDescription: 'Blanco con crianza de la tradición rioiana',
        type: 'blanco',
        price: 26.5,
        comparePrice: 34.0,
        stock: 65,
        alcoholDegree: 12.5,
        production: 'Rioja',
        temperature: '10-12°C',
        aging: '6 meses en barrica de roble',
        bodyLevel: 3,
        tanninLevel: 0,
        sweetnessLevel: 1,
        acidityLevel: 3,
        sight: 'Amarillo dorado intenso',
        nose: 'Manzana dorada, avellana, vainilla discreta',
        mouth: 'Redondo, con cuerpo, acidez equilibrada, final persistente',
        pairing: 'Quesos semicurados, jamón ibérico, pescados a la sal',
        image: '/products/viura-murrieta.jpg',
        format: '0,75L',
        vintage: '2021',
        availableVintages: ['2021', '2020'],
        availableFormats: ['0,75L'],
        bodegaId: bodegas[2].id,
        regionId: regions[1].id,
      },
    }),
    // Rosados
    prisma.product.create({
      data: {
        name: 'Rosado Navarra 2023',
        slug: 'rosado-navarra-2023',
        tagline: 'Rosado seco de calidad',
        description:
          'Rosado de Navarra elaborado con Garnacha. Color frambuesa pálido. Aromas de frutas rojas frescas y flores silvestres. Perfecto para verano.',
        shortDescription: 'Rosado fresco y versátil',
        type: 'rosado',
        price: 14.99,
        comparePrice: 19.0,
        stock: 180,
        isNew: true,
        alcoholDegree: 12.5,
        production: 'Navarra',
        temperature: '8-10°C',
        aging: 'Sin envejecimiento',
        bodyLevel: 2,
        tanninLevel: 1,
        sweetnessLevel: 1,
        acidityLevel: 3,
        sight: 'Rosa pálido, cristalino',
        nose: 'Fresas, flores de primavera, cítricos',
        mouth: 'Fresco, afrutado, acidez agradable',
        pairing: 'Ensaladas, carnes blancas ligeras, pescados, tapas variadas',
        image: '/products/rosado-navarra.jpg',
        format: '0,75L',
        vintage: '2023',
        availableVintages: ['2023', '2022'],
        availableFormats: ['0,75L'],
        bodegaId: bodegas[0].id,
        regionId: regions[1].id,
      },
    }),
    // Espumosos
    prisma.product.create({
      data: {
        name: 'Cava Brut Nature 2022',
        slug: 'cava-brut-nature-2022',
        tagline: 'Espumoso catalán de tradición',
        description:
          'Cava elaborado con método champenoise. Mezcla de Macabeo, Xarel·lo y Parellada. Espuma fina y persistente. Aromas frescos y minerales. Sin dosificación.',
        shortDescription: 'Espumoso de gran finura',
        type: 'espumoso',
        price: 19.5,
        comparePrice: 25.0,
        stock: 200,
        isRecommended: true,
        alcoholDegree: 12.0,
        production: 'Penedès',
        temperature: '6-8°C',
        aging: '30 meses de tiempos en botella',
        bodyLevel: 2,
        tanninLevel: 0,
        sweetnessLevel: 0,
        acidityLevel: 4,
        sight: 'Amarillo pálido con burbujas vivaces',
        nose: 'Frutas blancas, manzana, anís, minerales',
        mouth: 'Fresco, burbujas finas, acidez vivificante',
        pairing: 'Aperitivo, jamón ibérico, quesos, mariscos',
        image: '/products/cava-brut.jpg',
        format: '0,75L',
        vintage: '2022',
        availableVintages: ['2022', '2021'],
        availableFormats: ['0,75L'],
        bodegaId: bodegas[3].id,
        regionId: regions[5].id,
      },
    }),
    prisma.product.create({
      data: {
        name: 'Champagne Brut 2018',
        slug: 'champagne-brut-2018',
        tagline: 'Espumoso francés clásico',
        description:
          'Champagne de grandes viñedos en la región de Champagne. Blend de Pinot Noir, Chardonnay y Pinot Meunier. Crianza prolongada con levaduras muertas. Complejidad y elegancia.',
        shortDescription: 'Champagne clásico de Francia',
        type: 'espumoso',
        price: 58.0,
        comparePrice: 72.0,
        stock: 50,
        isRecommended: true,
        alcoholDegree: 12.5,
        production: 'Champagne',
        temperature: '6-8°C',
        aging: '36 meses de tiempos en botella',
        bodyLevel: 3,
        tanninLevel: 0,
        sweetnessLevel: 1,
        acidityLevel: 4,
        sight: 'Oro pálido con burbujas abundantes y finas',
        nose: 'Brioche, frutas blancas secas, minerales, especias',
        mouth: 'Elegante y complejo, acidez noble, persistencia excepcional',
        pairing: 'Aperitivo de lujo, ostras, langostinos, postres ligeros',
        image: '/products/champagne-brut.jpg',
        format: '0,75L',
        vintage: '2018',
        availableVintages: ['2018', '2016'],
        availableFormats: ['0,75L'],
        bodegaId: bodegas[9].id,
        regionId: regions[6].id,
      },
    }),
    // Destilados y especiales
    prisma.product.create({
      data: {
        name: 'Brandy de Jerez Solera 1842',
        slug: 'brandy-jerez-solera-1842',
        tagline: 'Brandy de solera histórica',
        description:
          'Brandy de Jerez envejecido en botas de roble según sistema de solera. Aromas complejos de madera, pasas, chocolate y especias. Destilado de gran complejidad.',
        shortDescription: 'Bebida espirituosa de gran refinamiento',
        type: 'destilado',
        price: 48.5,
        comparePrice: 62.0,
        stock: 35,
        alcoholDegree: 36.0,
        production: 'Jerez de la Frontera',
        temperature: '16-18°C',
        aging: 'Solera de más de 150 años',
        bodyLevel: 5,
        tanninLevel: 0,
        sweetnessLevel: 2,
        acidityLevel: 1,
        sight: 'Ámbar oscuro, traslúcido',
        nose: 'Roble, pasas, chocolate, vainilla, especias oscuras',
        mouth: 'Cálido, untuoso, final largo y cautivador',
        pairing: 'Solo, con hielo, postres de chocolate, tabacos',
        image: '/products/brandy-jerez.jpg',
        format: '0,70L',
        availableFormats: ['0,70L'],
        bodegaId: bodegas[0].id,
        regionId: regions[1].id,
      },
    }),
    prisma.product.create({
      data: {
        name: 'Jerez Fino Tío Pepe',
        slug: 'jerez-fino-tio-pepe',
        tagline: 'Fino clásico de Jerez',
        description:
          'Vino generoso Fino elaborado en Jerez. Envejecimiento bajo velo de levaduras. Seco y elegante con aromas de almendras y minerales. Tradicional de Andalucía.',
        shortDescription: 'Generoso seco por excelencia',
        type: 'generoso',
        price: 22.0,
        comparePrice: 28.0,
        stock: 90,
        alcoholDegree: 15.0,
        production: 'Jerez de la Frontera',
        temperature: '10-12°C',
        aging: 'Solera dinámica de más de 200 años',
        bodyLevel: 2,
        tanninLevel: 0,
        sweetnessLevel: 0,
        acidityLevel: 3,
        sight: 'Amarillo pálido, cristalino',
        nose: 'Almendras frescas, manzana, minerales, levaduras',
        mouth: 'Seco, fresco, salivante, final persistente',
        pairing: 'Jamón ibérico, anchoas, quesos semicurados, jamón serrano',
        image: '/products/fino-tio-pepe.jpg',
        format: '0,75L',
        availableFormats: ['0,75L'],
        bodegaId: bodegas[0].id,
        regionId: regions[1].id,
      },
    }),
    prisma.product.create({
      data: {
        name: 'Jerez Amontillado Viejo',
        slug: 'jerez-amontillado-viejo',
        tagline: 'Generoso en su máxima expresión',
        description:
          'Amontillado envejecido bajo velo de flor y posterior oxidación. Color oscuro y aromas evolucionados de café, pasas y nueces. Complejidad excepcional.',
        shortDescription: 'Generoso de gran carácter y complejidad',
        type: 'generoso',
        price: 35.75,
        comparePrice: 46.0,
        stock: 55,
        alcoholDegree: 16.5,
        production: 'Jerez de la Frontera',
        temperature: '12-14°C',
        aging: 'Solera con más de 25 años de envejecimiento',
        bodyLevel: 3,
        tanninLevel: 0,
        sweetnessLevel: 1,
        acidityLevel: 2,
        sight: 'Ámbar dorado oscuro',
        nose: 'Café, pasas, nueces, especias, minerales',
        mouth: 'Complejo, cálido, notas de almendruco, final largo',
        pairing: 'Solo, quesos azules, foie gras, carne de caza',
        image: '/products/amontillado-viejo.jpg',
        format: '0,75L',
        availableFormats: ['0,75L'],
        bodegaId: bodegas[0].id,
        regionId: regions[1].id,
      },
    }),
    // Más tintos para completar 50 productos
    prisma.product.create({
      data: {
        name: 'Cabernet Sauvignon Château Margaux 2019',
        slug: 'margaux-2019',
        tagline: 'Burdeos de legendaria clase',
        description:
          'Uno de los mejores vinos del mundo. Cabernet Sauvignon que expresa la elegancia de Burdeos izquierdo. Aromas de cassis, violetas y tabaco. Estructura magnífica.',
        shortDescription: 'Vino legendario de Burdeos',
        type: 'tinto',
        price: 280.0,
        comparePrice: 350.0,
        stock: 8,
        isRecommended: true,
        isFeatured: true,
        alcoholDegree: 13.5,
        production: 'Burdeos, Margaux',
        temperature: '18°C',
        aging: '18 meses en barrica nueva',
        wood: 'Roble francés 100%',
        bodyLevel: 4,
        tanninLevel: 4,
        sweetnessLevel: 1,
        acidityLevel: 3,
        sight: 'Rojo púrpura intenso',
        nose: 'Cassis, violeta, tabaco, cedro, grosella negra',
        mouth: 'Elegante y estructurado, tánicos sedosos',
        pairing: 'Carnes rojas de calidad, cordero, pato, quesos curados',
        image: '/products/margaux-2019.jpg',
        format: '0,75L',
        vintage: '2019',
        availableVintages: ['2019', '2018', '2016'],
        availableFormats: ['0,75L'],
        bodegaId: bodegas[9].id,
        regionId: regions[7].id,
      },
    }),
    prisma.product.create({
      data: {
        name: 'Priorat Garnacha Vieja Parcelas 2020',
        slug: 'priorat-garnacha-parcelas-2020',
        tagline: 'Garnacha centenaria de pizarra',
        description:
          'Garnacha de viñas centenarias en Priorat. Fermentación natural, sin adiciones. Frutas negras secas, especias oscuras y mineralidad de pizarra.',
        shortDescription: 'Expresión pura de viñas antiguas',
        type: 'tinto',
        price: 55.0,
        comparePrice: 70.0,
        stock: 40,
        alcoholDegree: 14.5,
        production: 'Priorat',
        temperature: '18°C',
        aging: '14 meses en ánfora de barro',
        bodyLevel: 5,
        tanninLevel: 4,
        sweetnessLevel: 1,
        acidityLevel: 3,
        sight: 'Rojo negro profundo',
        nose: 'Frutas negras desecadas, pizarra, almíbar',
        mouth: 'Concentrado, tánicos rugosos, mineral',
        pairing: 'Cordero asado, carne de caza, quesos muy curados',
        image: '/products/priorat-garnacha.jpg',
        format: '0,75L',
        vintage: '2020',
        availableVintages: ['2020', '2019'],
        availableFormats: ['0,75L'],
        bodegaId: bodegas[4].id,
        regionId: regions[2].id,
      },
    }),
    prisma.product.create({
      data: {
        name: 'Bierzo Mencía Fermentación Natural 2021',
        slug: 'bierzo-mencia-natural-2021',
        tagline: 'Mencía sin intervención',
        description:
          'Mencía producida con mínima intervención. Fermentación espontánea con levaduras silvestres. Fresco, mineral y dinámico. Vino que evoluciona en copa.',
        shortDescription: 'Vino natural de gran expresión',
        type: 'tinto',
        price: 28.5,
        comparePrice: 38.0,
        stock: 65,
        alcoholDegree: 13.0,
        production: 'Bierzo',
        temperature: '16°C',
        aging: 'Fermentación y tiempos espontáneos',
        filtration: 'Sin filtrar ni clarificar',
        bodyLevel: 3,
        tanninLevel: 2,
        sweetnessLevel: 1,
        acidityLevel: 4,
        sight: 'Rojo rubí turbio',
        nose: 'Frutas rojas frescas, flores, especias, minerales',
        mouth: 'Fresco y ligero, tánicos sedosos, mineral predominante',
        pairing: 'Quesos de oveja, embutidos artesanales, legumbres, pescados',
        image: '/products/bierzo-mencia-natural.jpg',
        format: '0,75L',
        vintage: '2021',
        availableVintages: ['2021', '2022'],
        availableFormats: ['0,75L'],
        bodegaId: bodegas[7].id,
        regionId: regions[3].id,
      },
    }),
    prisma.product.create({
      data: {
        name: 'Ribera del Duero Tinto Joven 2022',
        slug: 'ribera-duero-joven-2022',
        tagline: 'Tinto joven de inmediata',
        description:
          'Tempranillo joven sin envejecimiento. Elaboración moderna para consumo inmediato. Frutas rojas frescas, ligero y versátil.',
        shortDescription: 'Vino fresco para beber en seguida',
        type: 'tinto',
        price: 12.75,
        comparePrice: 17.0,
        stock: 200,
        alcoholDegree: 13.0,
        production: 'Ribiera del Duero',
        temperature: '16°C',
        aging: 'Sin envejecimiento',
        bodyLevel: 2,
        tanninLevel: 2,
        sweetnessLevel: 1,
        acidityLevel: 3,
        sight: 'Rojo cereza vivo',
        nose: 'Frambuesa, fresa, hierbas frescas',
        mouth: 'Afrutado, fresco, tánicos suaves',
        pairing: 'Carnes a la parrilla, pastas, quesos tiernos, tapas',
        image: '/products/ribera-joven.jpg',
        format: '0,75L',
        vintage: '2022',
        availableVintages: ['2022', '2021'],
        availableFormats: ['0,75L'],
        bodegaId: bodegas[0].id,
        regionId: regions[0].id,
      },
    }),
    prisma.product.create({
      data: {
        name: 'Rioja Gran Reserva Centenario 2014',
        slug: 'rioja-gran-reserva-2014',
        tagline: 'Rioja de envejecimiento extremo',
        description:
          'Gran Reserva de Rioja con 10 años de envejecimiento combinando barrica y botella. Complejidad evolucionada con aromas terciarios nobles.',
        shortDescription: 'Para coleccionistas de vinos evolucionados',
        type: 'tinto',
        price: 125.0,
        comparePrice: 160.0,
        stock: 20,
        isRecommended: true,
        alcoholDegree: 13.5,
        production: 'Rioja',
        temperature: '18°C',
        aging: '5 años en barrica, 5 años en botella',
        bodyLevel: 4,
        tanninLevel: 3,
        sweetnessLevel: 1,
        acidityLevel: 3,
        sight: 'Rojo teja profundo',
        nose: 'Compota, cuero, tamarisco, minerales evolucionados',
        mouth: 'Sedoso, evoluciona en boca, final extraordinario',
        pairing: 'Pato asado, caza, quesos blandos, setas',
        image: '/products/rioja-gran-reserva.jpg',
        format: '0,75L',
        vintage: '2014',
        availableVintages: ['2014'],
        availableFormats: ['0,75L'],
        bodegaId: bodegas[2].id,
        regionId: regions[1].id,
      },
    }),
    // Más blancos
    prisma.product.create({
      data: {
        name: 'Sauvignon Blanc Rueda 2023',
        slug: 'sauvignon-blanc-rueda-2023',
        tagline: 'Blanco aromático de Castilla',
        description:
          'Sauvignon Blanc en Rueda, demostrando versatilidad regional. Aromas herbáceos, cítricos y tropicales. Fresco y expresivo.',
        shortDescription: 'Blanco internacional en contexto español',
        type: 'blanco',
        price: 19.99,
        comparePrice: 26.0,
        stock: 85,
        alcoholDegree: 13.0,
        production: 'Rueda',
        temperature: '8-10°C',
        aging: 'Sin envejecimiento',
        bodyLevel: 2,
        tanninLevel: 0,
        sweetnessLevel: 1,
        acidityLevel: 4,
        sight: 'Amarillo verdoso cristalino',
        nose: 'Herbáceo, grosellas blancas, piña, cítricos',
        mouth: 'Vivaz, aromatic, acidez refrescante',
        pairing: 'Espárragos, alcachofas, quesos frescos, pescados blancos',
        image: '/products/sauvignon-blanc-rueda.jpg',
        format: '0,75L',
        vintage: '2023',
        availableVintages: ['2023', '2022'],
        availableFormats: ['0,75L'],
        bodegaId: bodegas[0].id,
        regionId: regions[4].id,
      },
    }),
    prisma.product.create({
      data: {
        name: 'Chardonnay Penedès 2021',
        slug: 'chardonnay-penedes-2021',
        tagline: 'Blanco envejecido en roble',
        description:
          'Chardonnay de Penedès con crianza en roble francés. Frutas blancas maduras, vainilla y notas de tostado bien integradas.',
        shortDescription: 'Blanco con estructura y crianza',
        type: 'blanco',
        price: 32.5,
        comparePrice: 42.0,
        stock: 50,
        alcoholDegree: 13.0,
        production: 'Penedès',
        temperature: '10-12°C',
        aging: '8 meses en roble francés',
        bodyLevel: 4,
        tanninLevel: 0,
        sweetnessLevel: 1,
        acidityLevel: 3,
        sight: 'Amarillo dorado intenso',
        nose: 'Manzana dorada, flores blancas, vainilla, avellana',
        mouth: 'Complejo, redondo, buena persistencia',
        pairing: 'Quesos semicurados, jamón ibérico, mariscos con salsas',
        image: '/products/chardonnay-penedes.jpg',
        format: '0,75L',
        vintage: '2021',
        availableVintages: ['2021', '2020'],
        availableFormats: ['0,75L'],
        bodegaId: bodegas[3].id,
        regionId: regions[5].id,
      },
    }),
    // Más rosados
    prisma.product.create({
      data: {
        name: 'Rosado Provenza Importado 2023',
        slug: 'rosado-provenza-2023',
        tagline: 'Rosado francés pálido',
        description:
          'Rosado de Provenza con color casi blanco. Delicado y fresco. Fresas, flores y minerales. Referencia del rosado mediterráneo.',
        shortDescription: 'Rosado de máxima sutileza',
        type: 'rosado',
        price: 24.99,
        comparePrice: 32.0,
        stock: 75,
        alcoholDegree: 12.5,
        production: 'Provenza, Francia',
        temperature: '8-10°C',
        aging: 'Sin envejecimiento',
        bodyLevel: 2,
        tanninLevel: 0,
        sweetnessLevel: 1,
        acidityLevel: 3,
        sight: 'Rosado pálido, casi salmón',
        nose: 'Fresas silvestres, flores, manzana',
        mouth: 'Delicado, floral, refrescante',
        pairing: 'Ensaladas, mariscos fríos, quesos frescos, alioli',
        image: '/products/rosado-provenza.jpg',
        format: '0,75L',
        vintage: '2023',
        availableVintages: ['2023', '2022'],
        availableFormats: ['0,75L'],
        bodegaId: bodegas[9].id,
        regionId: regions[7].id,
      },
    }),
    // Más espumosos
    prisma.product.create({
      data: {
        name: 'Cava Rosado Brut 2021',
        slug: 'cava-rosado-brut-2021',
        tagline: 'Espumoso rosado de calidad',
        description:
          'Cava rosado elaborado con Trepat. Color frambuesa intenso. Fresas y flores en nariz. Espuma persistente y fina.',
        shortDescription: 'Espumoso rosado festivo',
        type: 'espumoso',
        price: 21.75,
        comparePrice: 28.0,
        stock: 90,
        alcoholDegree: 12.0,
        production: 'Penedès',
        temperature: '6-8°C',
        aging: '24 meses en botella',
        bodyLevel: 2,
        tanninLevel: 0,
        sweetnessLevel: 1,
        acidityLevel: 4,
        sight: 'Rosado frambuesa con burbujas vivas',
        nose: 'Fresas, flores de primavera, frutas rojas',
        mouth: 'Afrutado, espuma fina, acidez vivificante',
        pairing: 'Aperitivo festivo, postres de frutas, fresas con nata',
        image: '/products/cava-rosado.jpg',
        format: '0,75L',
        vintage: '2021',
        availableVintages: ['2021', '2020'],
        availableFormats: ['0,75L'],
        bodegaId: bodegas[3].id,
        regionId: regions[5].id,
      },
    }),
    prisma.product.create({
      data: {
        name: 'Prosecco Brut Importado 2022',
        slug: 'prosecco-brut-2022',
        tagline: 'Espumoso italiano alegre',
        description:
          'Prosecco italiano de método Charmat. Frutas blancas y flores. Burbujas abundantes. Ideal para brindis.',
        shortDescription: 'Espumoso desenfadado italiano',
        type: 'espumoso',
        price: 16.5,
        comparePrice: 21.0,
        stock: 110,
        alcoholDegree: 11.5,
        production: 'Venecia, Italia',
        temperature: '6-8°C',
        aging: '3 meses en botella',
        bodyLevel: 2,
        tanninLevel: 0,
        sweetnessLevel: 1,
        acidityLevel: 3,
        sight: 'Amarillo pálido con burbujas abundantes',
        nose: 'Manzana, pera, flores, miel',
        mouth: 'Fresco, afrutado, burbujas abundantes',
        pairing: 'Aperitivo, brindis, frutas, postres ligeros',
        image: '/products/prosecco-brut.jpg',
        format: '0,75L',
        vintage: '2022',
        availableVintages: ['2022', '2021'],
        availableFormats: ['0,75L'],
        bodegaId: bodegas[0].id,
        regionId: regions[6].id,
      },
    }),
    // Vinos especiales y de postre
    prisma.product.create({
      data: {
        name: 'Jerez Oloroso Viejo Rareza',
        slug: 'jerez-oloroso-viejo',
        tagline: 'Generoso oscuro de solera',
        description:
          'Oloroso envejecido en solera durante décadas. Oscuro y aromático con notas de avellana, café y chocolate oscuro. Vino para saborear.',
        shortDescription: 'Generoso de complejidad máxima',
        type: 'generoso',
        price: 42.0,
        comparePrice: 55.0,
        stock: 30,
        isRecommended: true,
        alcoholDegree: 17.0,
        production: 'Jerez de la Frontera',
        temperature: '14-16°C',
        aging: 'Solera con más de 40 años',
        bodyLevel: 5,
        tanninLevel: 0,
        sweetnessLevel: 1,
        acidityLevel: 2,
        sight: 'Ámbar muy oscuro, casi opaco',
        nose: 'Avellana, café, cacao, minerales, cuero',
        mouth: 'Cálido y untuoso, notas de chocolate, final épico',
        pairing: 'Solo, quesos azules, foie gras, cacao',
        image: '/products/oloroso-viejo.jpg',
        format: '0,75L',
        availableFormats: ['0,75L'],
        bodegaId: bodegas[0].id,
        regionId: regions[1].id,
      },
    }),
    prisma.product.create({
      data: {
        name: 'Moscatel de Valencia Dulce',
        slug: 'moscatel-valencia-dulce',
        tagline: 'Vino dulce de uva moscatel',
        description:
          'Vino dulce elaborado con Moscatel de Alejandría. Fermentación detenida. Aromas florales intensos y notas de miel.',
        shortDescription: 'Vino de postre suave y aromático',
        type: 'dulce',
        price: 18.5,
        comparePrice: 24.0,
        stock: 65,
        alcoholDegree: 11.0,
        production: 'Valencia',
        temperature: '8-10°C',
        bodyLevel: 3,
        tanninLevel: 0,
        sweetnessLevel: 5,
        acidityLevel: 2,
        sight: 'Ámbar dorado claro',
        nose: 'Moscatel, flores, miel, uvas pasas',
        mouth: 'Dulce pero equilibrado, aromatic, final persistente',
        pairing: 'Postres de frutas, almíbares, quesos blandos, frutos secos',
        image: '/products/moscatel-valencia.jpg',
        format: '0,75L',
        vintage: 'N.V.',
        availableFormats: ['0,75L'],
        bodegaId: bodegas[0].id,
        regionId: regions[4].id,
      },
    }),
    prisma.product.create({
      data: {
        name: 'Pedro Ximénez Jerez Dulce',
        slug: 'pedro-ximenez-jerez-dulce',
        tagline: 'Vino de postre dulce y aromático',
        description:
          'Pedro Ximénez asoleado antes de fermentación. Muy dulce, denso y aromático. Pasas, higos y chocolate. Postre en botella.',
        shortDescription: 'Vino de postre con carácter',
        type: 'dulce',
        price: 28.75,
        comparePrice: 37.0,
        stock: 45,
        alcoholDegree: 15.0,
        production: 'Jerez de la Frontera',
        temperature: '10-12°C',
        aging: 'Solera de más de 20 años',
        bodyLevel: 5,
        tanninLevel: 0,
        sweetnessLevel: 5,
        acidityLevel: 1,
        sight: 'Negro casi opaco, reflejos rojizos',
        nose: 'Pasas, higos, dátiles, chocolate, toffee',
        mouth: 'Muy dulce pero balanceado, denso, persistente',
        pairing: 'Postres de chocolate, quesos blandos, almendras, nueces',
        image: '/products/pedro-ximenez.jpg',
        format: '0,75L',
        availableFormats: ['0,75L'],
        bodegaId: bodegas[0].id,
        regionId: regions[1].id,
      },
    }),
    prisma.product.create({
      data: {
        name: 'Riojas Altas Tinto Reserva 2018',
        slug: 'riojas-altas-reserva-2018',
        tagline: 'Tinto de la zona noble de Rioja',
        description:
          'Tempranillo de Rioja Alta con envejecimiento prolongado. Frutas maduras, especias y notas de cuero. Elegancia rioiana.',
        shortDescription: 'Tinto noble de Rioja Alta',
        type: 'tinto',
        price: 38.5,
        comparePrice: 50.0,
        stock: 70,
        alcoholDegree: 13.5,
        production: 'Rioja Alta',
        temperature: '17°C',
        aging: '24 meses en roble',
        wood: 'Roble francés',
        bodyLevel: 3,
        tanninLevel: 3,
        sweetnessLevel: 1,
        acidityLevel: 3,
        sight: 'Rojo rubí profundo',
        nose: 'Ciruela, especias, cedro, vainilla sutil',
        mouth: 'Equilibrado, tánicos redondos, final noble',
        pairing: 'Carnes rojas, pato, quesos semicurados',
        image: '/products/riojas-altas-reserva.jpg',
        format: '0,75L',
        vintage: '2018',
        availableVintages: ['2018', '2017'],
        availableFormats: ['0,75L'],
        bodegaId: bodegas[5].id,
        regionId: regions[1].id,
      },
    }),
    prisma.product.create({
      data: {
        name: 'Vino Blanco Albariño Premium 2022',
        slug: 'albarino-premium-2022',
        tagline: 'Albariño de parcela',
        description:
          'Albariño seleccionado de una parcela histórica. Minerales intensos, frutas blancas y salinidad marina. Complejidad en blanco.',
        shortDescription: 'Albariño de expresión única',
        type: 'blanco',
        price: 31.5,
        comparePrice: 41.0,
        stock: 55,
        alcoholDegree: 13.0,
        production: 'Rías Baixas',
        temperature: '9-11°C',
        aging: '6 meses en acero con batonnage',
        bodyLevel: 3,
        tanninLevel: 0,
        sweetnessLevel: 1,
        acidityLevel: 4,
        sight: 'Amarillo dorado pálido',
        nose: 'Frutas blancas, minerales, sal marina, almendra',
        mouth: 'Complejo, mineral predominante, acidez noble',
        pairing: 'Mariscos variados, langostinos, percebes, ostras',
        image: '/products/albarino-premium.jpg',
        format: '0,75L',
        vintage: '2022',
        availableVintages: ['2022', '2021'],
        availableFormats: ['0,75L'],
        bodegaId: bodegas[0].id,
        regionId: regions[4].id,
      },
    }),
  ])

  // Create some ratings for products
  for (let i = 0; i < 15; i++) {
    const product = products[Math.floor(Math.random() * products.length)]
    const critics = ['Parker', 'Suckling', 'Peñín', 'Tim Atkin', 'Jancis Robinson']
    const scores = [86, 88, 90, 92, 94, 95, 96, 97, 98, 99]

    await prisma.rating.create({
      data: {
        productId: product.id,
        critic: critics[Math.floor(Math.random() * critics.length)],
        score: scores[Math.floor(Math.random() * scores.length)],
        vintage: product.vintage || '2021',
        note: 'Excelente vino con características sobresalientes',
      },
    })
  }

  // Create blog posts
  const blogPosts = await Promise.all([
    prisma.blogPost.create({
      data: {
        title: 'Guía completa de Ribera del Duero',
        slug: 'guia-ribera-duero',
        excerpt: 'Descubre la historia, terroir y vinos de una de las regiones más prestigiosas de España.',
        content:
          'Ribera del Duero es una región vitivinícola de Castilla y León con una historia vinífera que se remonta siglos atrás. Ubicada en el valle del río Duero, la región se caracteriza por sus viñedos en pendientes empinadas y altitudes entre 700 y 900 metros. El clima continental extremo, con inviernos rigurosos y veranos cálidos, es fundamental para la expresión de los vinos Tempranillo de gran calidad.',
        author: 'Casa del Vino',
        tags: ['Ribera del Duero', 'Vino Tinto', 'España'],
        published: true,
      },
    }),
    prisma.blogPost.create({
      data: {
        title: 'Maridaje: Vino Blanco con Mariscos',
        slug: 'maridaje-blanco-mariscos',
        excerpt: 'Aprende a combinar los mejores vinos blancos con tus platos de marisco favoritos.',
        content:
          'El maridaje es el arte de combinar alimentos y bebidas para potenciar mutuamente sus sabores. En el caso de los mariscos, los vinos blancos son siempre la elección más segura. Los Albariños de Rías Baixas con su mineralidad y salinidad son perfectos para mariscos a la gallega, mientras que los Verdejo de Rueda funcionan bien con cefalópodos.',
        author: 'Casa del Vino',
        tags: ['Maridaje', 'Vino Blanco', 'Mariscos'],
        published: true,
      },
    }),
    prisma.blogPost.create({
      data: {
        title: 'Historia del Vino de Jerez',
        slug: 'historia-vino-jerez',
        excerpt: 'Conoce la fascinante historia de los vinos generosos de Jerez desde la antigüedad.',
        content:
          'El vino de Jerez tiene una historia que se remonta a los fenicios y romanos. Sin embargo, fue en la Edad Media cuando los vinos de Jerez ganaron fama internacional. Los vinos fortified de Jerez incluyen Fino, Amontillado, Oloroso y Pedro Ximénez, cada uno con características únicas desarrolladas bajo el sistema de solera.',
        author: 'Casa del Vino',
        tags: ['Jerez', 'Vino Generoso', 'Historia'],
        published: true,
      },
    }),
    prisma.blogPost.create({
      data: {
        title: 'Cómo degustar un vino como experto',
        slug: 'como-degustar-vino',
        excerpt: 'Los pasos esenciales para degustar vino de manera profesional y apreciar sus características.',
        content:
          'La degustación de vino es un proceso que implica cuatro pasos principales: observación visual, aromas, sabor y conclusión. Primero, observa el color, claridad y densidad. Luego, huele el vino para identificar aromas primarios, secundarios y terciarios. Finalmente, pruébalo dejando que cubra toda tu boca para apreciar la estructura, acidez y tánicos.',
        author: 'Casa del Vino',
        tags: ['Degustación', 'Técnica', 'Educación Vino'],
        published: true,
      },
    }),
    prisma.blogPost.create({
      data: {
        title: 'Vinos naturales: ¿qué son y por qué gustan?',
        slug: 'vinos-naturales-explicado',
        excerpt: 'Entiende el movimiento de vinos naturales y por qué cada vez más amantes del vino los eligen.',
        content:
          'Los vinos naturales son vinos producidos con mínima intervención humana. Utilizan levaduras silvestres, no añaden sulfitos (o añaden cantidades mínimas), y no se filtran. Esto resulta en vinos dinámicos, frescos y con mayor expresión de terroir. Aunque pueden ser más variables, apasionan a muchos amantes del vino por su autenticidad.',
        author: 'Casa del Vino',
        tags: ['Vinos Naturales', 'Sostenibilidad', 'Tendencias'],
        published: true,
      },
    }),
    prisma.blogPost.create({
      data: {
        title: 'Almacenamiento y conservación del vino',
        slug: 'almacenamiento-vino',
        excerpt: 'Consejos prácticos para guardar tus botellas en óptimas condiciones.',
        content:
          'El almacenamiento adecuado es crucial para preservar la calidad del vino. Los vinos deben guardarse en posición horizontal (excepto espumosos), a temperatura constante entre 10-15°C, alejados de luz directa y vibraciones. Una bodega o nevera vino es ideal, aunque un closet fresco también funciona.',
        author: 'Casa del Vino',
        tags: ['Almacenamiento', 'Conservación', 'Consejos Prácticos'],
        published: true,
      },
    }),
    prisma.blogPost.create({
      data: {
        title: 'Las regiones vitivinícolas de Francia',
        slug: 'regiones-vino-francia',
        excerpt: 'Recorre las principales regiones vitivinícolas francesas y sus características distintivas.',
        content:
          'Francia es el país vitivinícola por excelencia. Burdeos, Borgoña, Champagne, Provenza y Valle del Loira son algunas de sus principales regiones. Cada una tiene su identidad propia: Burdeos es conocido por sus Cabernet Sauvignon; Borgoña por sus Pinot Noir y Chardonnay; Champagne por sus espumosos; Provenza por sus rosados.',
        author: 'Casa del Vino',
        tags: ['Francia', 'Regiones Vitivinícolas', 'Geografía Vino'],
        published: true,
      },
    }),
    prisma.blogPost.create({
      data: {
        title: 'Descubriendo Priorat: minería de piedra y vino',
        slug: 'descubriendo-priorat',
        excerpt: 'Explora la pequeña pero legendaria región vitivinícola de Priorat en Cataluña.',
        content:
          'Priorat es una región muy pequeña en Tarragona conocida por producir algunos de los vinos más buscados de España. Sus viñedos se cultivan en laderas empinadas sobre terrenos de pizarra conocida como "llicorella". La mineralidad es la característica distintiva de los vinos de Priorat, especialmente los elaborados con Garnacha.',
        author: 'Casa del Vino',
        tags: ['Priorat', 'Cataluña', 'Viñedos Empinados'],
        published: true,
      },
    }),
    prisma.blogPost.create({
      data: {
        title: 'Cava vs Champagne: ¿cuál es la diferencia?',
        slug: 'cava-vs-champagne',
        excerpt: 'Compara estos dos espumosos icónicos y descubre qué los hace únicos.',
        content:
          'Aunque ambos se elaboran con el mismo método champenoise, hay diferencias clave. El Champagne proviene de Francia, específicamente de la región de Champagne, con regulaciones muy estrictas. El Cava es español, principalmente de Cataluña, y utiliza diferentes variedades de uva (Macabeo, Xarel·lo, Parellada). El Cava es generalmente más accesible en precio.',
        author: 'Casa del Vino',
        tags: ['Espumosos', 'Cava', 'Champagne', 'Comparación'],
        published: true,
      },
    }),
    prisma.blogPost.create({
      data: {
        title: 'Espumosos españoles: más allá del Cava',
        slug: 'espumosos-espanoles-mas-alla-cava',
        excerpt: 'Descubre la diversidad de espumosos españoles además del conocido Cava.',
        content:
          'España produce muchos espumosos además de Cava. Penedès, Conca de Barberà y Requena tienen sus propios espumosos con características únicas. Algunos productores artesanales utilizan método tradicional con fermentación en botella para crear espumosos de mayor complejidad. La innovación en la producción de espumosos españoles continúa sorprendiendo a críticos y amantes del vino.',
        author: 'Casa del Vino',
        tags: ['Espumosos', 'España', 'Innovación'],
        published: true,
      },
    }),
    prisma.blogPost.create({
      data: {
        title: 'Entendiendo los tánicos del vino',
        slug: 'entendiendo-tanicos-vino',
        excerpt: 'Aprende qué son los tánicos, de dónde vienen y cómo afectan el sabor del vino.',
        content:
          'Los tánicos son compuestos naturales que se encuentran en la piel, semillas y tallos de las uvas. Crean una sensación de sequedad o astringencia en la boca. Los vinos tintos suelen tener más tánicos que los blancos debido al contacto prolongado con el hollejo. Con el tiempo, los tánicos se suavizan, lo que permite que los vinos mejoren con la edad.',
        author: 'Casa del Vino',
        tags: ['Composición Vino', 'Tánicos', 'Características'],
        published: true,
      }),
    prisma.blogPost.create({
      data: {
        title: 'Bodegas familiares: tradición y pasión',
        slug: 'bodegas-familiares',
        excerpt: 'Conoce historias de bodegas pequeñas y familiares que mantienen viva la tradición vinífera.',
        content:
          'Muchas de las mejores bodegas del mundo son negocios familiares transmitidos de generación en generación. Estas bodegas mantienen técnicas tradicionales y un profundo respeto por la tierra y el vino. Su compromiso con la calidad sobre la cantidad ha resultado en vinos de reputación mundial.',
        author: 'Casa del Vino',
        tags: ['Bodegas Familiares', 'Tradición', 'España'],
        published: true,
      }),
    prisma.blogPost.create({
      data: {
        title: 'Envejecimiento del vino: barrica vs botella',
        slug: 'envejecimiento-vino-barrica-botella',
        excerpt: 'Entiende cómo y dónde envejece el vino, y qué diferencia hay entre ambos métodos.',
        content:
          'El envejecimiento en barrica permite que el vino se oxyde moderadamente, desarrolle sabores más complejos y adquiera notas de madera. El envejecimiento en botella es un proceso más lento y gradual que permite que los sabores se integren y evolucionen. Diferentes regiones tienen diferentes regulaciones sobre tiempo de barrica requerido.',
        author: 'Casa del Vino',
        tags: ['Envejecimiento', 'Barrica', 'Proceso Vino'],
        published: true,
      }),
    prisma.blogPost.create({
      data: {
        title: 'Sostenibilidad en viñedos españoles',
        slug: 'sostenibilidad-vinedos-espanoles',
        excerpt: 'Descubre cómo muchas bodegas españolas son líderes en prácticas sostenibles.',
        content:
          'Muchas bodegas españolas han adoptado prácticas sostenibles como agricultura ecológica, reducción de agua, energías renovables y preservación del terroir. Estas prácticas no solo benefician al medio ambiente sino que también resultan en vinos de mayor calidad y autenticidad.',
        author: 'Casa del Vino',
        tags: ['Sostenibilidad', 'Ecología', 'Bodegas Responsables'],
        published: true,
      }),
    prisma.blogPost.create({
      data: {
        title: 'Las variedades de uva español: Tempranillo, Garnacha y más',
        slug: 'variedades-uva-espanol',
        excerpt: 'Conoce las principales variedades de uva cultivadas en España y su potencial.',
        content:
          'España es hogar de muchas variedades de uva autóctonas. Tempranillo es la más conocida, especialmente en Ribera del Duero y Rioja. Garnacha aporta cuerpo y especias. Mencía destaca en el Bierzo con frescura mineral. Albariño en Rías Baixas produce algunos de los mejores blancos del país. Cada variedad tiene características distintivas que reflejan su terroir.',
        author: 'Casa del Vino',
        tags: ['Variedades Uva', 'España', 'Viticultura'],
        published: true,
      }),
  ])

  // Create Packs
  const packs = await Promise.all([
    prisma.pack.create({
      data: {
        name: 'Pack Iniciación al Vino Tinto',
        slug: 'pack-iniciacion-tinto',
        description: 'Ideal para iniciarse en el mundo de los vinos tintos españoles. Contiene 3 botellas de regiones diferentes.',
        image: '/packs/iniciacion-tinto.jpg',
        price: 49.99,
        comparePrice: 65.0,
        active: true,
        products: {
          create: [
            { productId: products[0].id, quantity: 1 },
            { productId: products[3].id, quantity: 1 },
            { productId: products[6].id, quantity: 1 },
          ],
        },
      },
    }),
    prisma.pack.create({
      data: {
        name: 'Pack Gourmet Blanco y Marisco',
        slug: 'pack-gourmet-blanco',
        description: 'Combinación perfecta de vinos blancos para acompañar tus mariscos favoritos.',
        image: '/packs/gourmet-blanco.jpg',
        price: 55.5,
        comparePrice: 72.0,
        active: true,
        products: {
          create: [
            { productId: products[7].id, quantity: 1 },
            { productId: products[8].id, quantity: 1 },
            { productId: products[9].id, quantity: 1 },
          ],
        },
      },
    }),
    prisma.pack.create({
      data: {
        name: 'Pack Espumosos Celebración',
        slug: 'pack-espumosos-celebracion',
        description: 'Tres espumosos para celebrar tus momentos especiales con estilo.',
        image: '/packs/espumosos-celebracion.jpg',
        price: 59.99,
        comparePrice: 78.0,
        active: true,
        products: {
          create: [
            { productId: products[19].id, quantity: 1 },
            { productId: products[20].id, quantity: 1 },
            { productId: products[29].id, quantity: 1 },
          ],
        },
      },
    }),
  ])

  // Create Discount Codes
  await Promise.all([
    prisma.discountCode.create({
      data: {
        code: 'BIENVENIDA15',
        type: 'percentage',
        value: 15,
        minPurchase: 50.0,
        maxUses: 100,
        active: true,
        expiresAt: new Date('2026-12-31'),
      },
    }),
    prisma.discountCode.create({
      data: {
        code: 'VINO20',
        type: 'fixed',
        value: 20.0,
        minPurchase: 100.0,
        maxUses: 50,
        active: true,
        expiresAt: new Date('2026-12-31'),
      },
    }),
    prisma.discountCode.create({
      data: {
        code: 'PRIMAVERA10',
        type: 'percentage',
        value: 10,
        minPurchase: 75.0,
        active: true,
        expiresAt: new Date('2026-06-30'),
      },
    }),
    prisma.discountCode.create({
      data: {
        code: 'TIENDAOFICIAL',
        type: 'percentage',
        value: 25,
        minPurchase: 200.0,
        maxUses: 200,
        active: true,
        expiresAt: new Date('2026-12-31'),
      },
    }),
  ])

  console.log('Seed completed successfully!')
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
