import React from 'react';
import {
  HeroSlider,
  CategoryIcons,
  TopSales,
  BestSellers,
  BlogPreview,
  InfoBanners,
  NewArrivals,
  OffersSection,
  Recommendations,
  ReferralBanner,
  SeoLinks,
} from '@/components/home';
import { TrustBadges } from '@/components/common/TrustBadges';
import { Product } from '@/types';

// Mock product data - Spanish wines for homepage display
const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Vega Sicilia Unico 2019',
    description: 'Vino tinto de crianza con DO Ribera del Duero',
    price: 89.99,
    comparePrice: 129.99,
    image: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=400&h=600&fit=crop',
    sku: 'VS-UNICO-2019',
    stock: 12,
    featured: true,
    bodegaId: '1',
    bodega: {
      id: '1',
      name: 'Vega Sicilia',
      description: 'Bodega legendaria',
      country: 'España',
      region: 'Ribera del Duero',
      founded: 1864,
      image: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=400&h=600&fit=crop',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    regionId: '1',
    region: {
      id: '1',
      name: 'Ribera del Duero',
      country: 'España',
      description: 'Una de las mejores regiones vinícolas de España',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    categoryId: '1',
    category: {
      id: '1',
      name: 'Vinos Tintos Premium',
      slug: 'vinos-tintos-premium',
      description: 'Vinos tintos de alta gama',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    grapeIds: ['1'],
    grapes: [
      {
        id: '1',
        name: 'Tempranillo',
        description: 'Uva tinta española',
        color: 'tinto',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    wineType: 'tinto',
    vintage: 2019,
    volume: 750,
    alcohol: 14.5,
    acidity: 3.8,
    ratings: [
      {
        id: '1',
        productId: '1',
        critic: 'Parker',
        score: 96,
        source: 'Robert Parker',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
  },
  {
    id: '2',
    name: 'Marqués de Murrieta 2018',
    description: 'Vino tinto crianza DO Rioja',
    price: 34.99,
    comparePrice: 45.99,
    image: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=400&h=600&fit=crop',
    sku: 'MM-2018',
    stock: 45,
    featured: true,
    bodegaId: '2',
    bodega: {
      id: '2',
      name: 'Marqués de Murrieta',
      description: 'Bodega histórica riojana',
      country: 'España',
      region: 'Rioja',
      founded: 1852,
      image: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=400&h=600&fit=crop',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    regionId: '2',
    region: {
      id: '2',
      name: 'Rioja',
      country: 'España',
      description: 'La región vitivinícola más famosa de España',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    categoryId: '1',
    category: {
      id: '1',
      name: 'Vinos Tintos',
      slug: 'vinos-tintos',
      description: 'Vinos tintos',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    grapeIds: ['1'],
    grapes: [
      {
        id: '1',
        name: 'Tempranillo',
        description: 'Uva tinta española',
        color: 'tinto',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    wineType: 'tinto',
    vintage: 2018,
    volume: 750,
    alcohol: 14,
    acidity: 3.6,
    ratings: [
      {
        id: '2',
        productId: '2',
        critic: 'Parker',
        score: 93,
        source: 'Robert Parker',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
  },
  {
    id: '3',
    name: 'Almaviva 2019',
    description: 'Vino tinto premium DO Priorat',
    price: 56.99,
    image: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=400&h=600&fit=crop',
    sku: 'ALM-2019',
    stock: 28,
    featured: true,
    bodegaId: '3',
    bodega: {
      id: '3',
      name: 'Almaviva',
      description: 'Bodega de Priorat',
      country: 'España',
      region: 'Priorat',
      founded: 2010,
      image: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=400&h=600&fit=crop',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    regionId: '3',
    region: {
      id: '3',
      name: 'Priorat',
      country: 'España',
      description: 'Pequeña pero prestigiosa región de Cataluña',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    categoryId: '1',
    category: {
      id: '1',
      name: 'Vinos Tintos',
      slug: 'vinos-tintos',
      description: 'Vinos tintos',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    grapeIds: ['1', '2'],
    grapes: [
      {
        id: '1',
        name: 'Garnacha',
        description: 'Uva tinta',
        color: 'tinto',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: '2',
        name: 'Cariñena',
        description: 'Uva tinta',
        color: 'tinto',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    wineType: 'tinto',
    vintage: 2019,
    volume: 750,
    alcohol: 15,
    acidity: 3.5,
    ratings: [
      {
        id: '3',
        productId: '3',
        critic: 'Parker',
        score: 92,
        source: 'Robert Parker',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
  },
  {
    id: '4',
    name: 'Albariño Martín Códax 2023',
    description: 'Vino blanco DO Rías Baixas',
    price: 12.99,
    comparePrice: 16.99,
    image: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=400&h=600&fit=crop',
    sku: 'ALB-MC-2023',
    stock: 120,
    featured: true,
    bodegaId: '4',
    bodega: {
      id: '4',
      name: 'Martín Códax',
      description: 'Bodega de Rías Baixas',
      country: 'España',
      region: 'Rías Baixas',
      founded: 1986,
      image: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=400&h=600&fit=crop',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    regionId: '4',
    region: {
      id: '4',
      name: 'Rías Baixas',
      country: 'España',
      description: 'Región de vinos blancos en Galicia',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    categoryId: '2',
    category: {
      id: '2',
      name: 'Vinos Blancos',
      slug: 'vinos-blancos',
      description: 'Vinos blancos',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    grapeIds: ['3'],
    grapes: [
      {
        id: '3',
        name: 'Albariño',
        description: 'Uva blanca gallega',
        color: 'blanco',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    wineType: 'blanco',
    vintage: 2023,
    volume: 750,
    alcohol: 12.5,
    acidity: 3.5,
    createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
  },
  {
    id: '5',
    name: 'Moët & Chandon Brut Imperial',
    description: 'Champagne francés de lujo',
    price: 39.99,
    comparePrice: 52.99,
    image: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=400&h=600&fit=crop',
    sku: 'MOET-BRUT',
    stock: 35,
    featured: true,
    bodegaId: '5',
    bodega: {
      id: '5',
      name: 'Moët & Chandon',
      description: 'Casa de champagne francesa',
      country: 'Francia',
      region: 'Champagne',
      founded: 1743,
      image: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=400&h=600&fit=crop',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    regionId: '5',
    region: {
      id: '5',
      name: 'Champagne',
      country: 'Francia',
      description: 'Región de champagne francés',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    categoryId: '3',
    category: {
      id: '3',
      name: 'Champagne',
      slug: 'champagne',
      description: 'Champagnes',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    grapeIds: ['4', '5', '6'],
    grapes: [
      {
        id: '4',
        name: 'Chardonnay',
        description: 'Uva blanca',
        color: 'blanco',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: '5',
        name: 'Pinot Noir',
        description: 'Uva tinta',
        color: 'tinto',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: '6',
        name: 'Pinot Meunier',
        description: 'Uva tinta',
        color: 'tinto',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    wineType: 'espumoso',
    vintage: 2023,
    volume: 750,
    alcohol: 12,
    acidity: 3.2,
    ratings: [
      {
        id: '5',
        productId: '5',
        critic: 'Parker',
        score: 91,
        source: 'Robert Parker',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    createdAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
  },
  {
    id: '6',
    name: 'Cava Freixenet Cordon Negro',
    description: 'Cava español de calidad',
    price: 8.99,
    comparePrice: 12.99,
    image: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=400&h=600&fit=crop',
    sku: 'FREIX-CN',
    stock: 250,
    featured: false,
    bodegaId: '6',
    bodega: {
      id: '6',
      name: 'Freixenet',
      description: 'Bodega de cava española',
      country: 'España',
      region: 'Penedès',
      founded: 1914,
      image: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=400&h=600&fit=crop',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    regionId: '6',
    region: {
      id: '6',
      name: 'Penedès',
      country: 'España',
      description: 'Región de cava en Cataluña',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    categoryId: '4',
    category: {
      id: '4',
      name: 'Cava',
      slug: 'cava',
      description: 'Cavas españoles',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    grapeIds: ['4', '7', '8'],
    grapes: [
      {
        id: '4',
        name: 'Chardonnay',
        description: 'Uva blanca',
        color: 'blanco',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: '7',
        name: 'Macabeo',
        description: 'Uva blanca',
        color: 'blanco',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: '8',
        name: 'Xarel.lo',
        description: 'Uva blanca',
        color: 'blanco',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    wineType: 'espumoso',
    vintage: 2023,
    volume: 750,
    alcohol: 11.5,
    acidity: 3.3,
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
  },
  {
    id: '7',
    name: 'Domaines Ott Château de Selle Rosé 2022',
    description: 'Vino rosé premium de Provence',
    price: 24.99,
    image: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=400&h=600&fit=crop',
    sku: 'DOTT-ROSE-2022',
    stock: 60,
    featured: true,
    bodegaId: '7',
    bodega: {
      id: '7',
      name: 'Domaines Ott',
      description: 'Bodega francesa de rosés',
      country: 'Francia',
      region: 'Provence',
      founded: 1912,
      image: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=400&h=600&fit=crop',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    regionId: '7',
    region: {
      id: '7',
      name: 'Provence',
      country: 'Francia',
      description: 'Región de rosados franceses',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    categoryId: '5',
    category: {
      id: '5',
      name: 'Vinos Rosé',
      slug: 'vinos-rose',
      description: 'Vinos rosé',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    grapeIds: ['9', '10'],
    grapes: [
      {
        id: '9',
        name: 'Grenache',
        description: 'Uva rosada',
        color: 'rosado',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: '10',
        name: 'Mourvèdre',
        description: 'Uva tinta',
        color: 'tinto',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    wineType: 'rosado',
    vintage: 2022,
    volume: 750,
    alcohol: 13,
    acidity: 3.4,
    ratings: [
      {
        id: '7',
        productId: '7',
        critic: 'Parker',
        score: 90,
        source: 'Robert Parker',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
  },
  {
    id: '8',
    name: 'Marqués de Riscal 2020',
    description: 'Vino tinto DO Rioja ecológico',
    price: 18.99,
    comparePrice: 25.99,
    image: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=400&h=600&fit=crop',
    sku: 'MR-2020',
    stock: 80,
    featured: false,
    bodegaId: '8',
    bodega: {
      id: '8',
      name: 'Marqués de Riscal',
      description: 'Bodega histórica riojana ecológica',
      country: 'España',
      region: 'Rioja',
      founded: 1860,
      image: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=400&h=600&fit=crop',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    regionId: '2',
    region: {
      id: '2',
      name: 'Rioja',
      country: 'España',
      description: 'La región vitivinícola más famosa de España',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    categoryId: '1',
    category: {
      id: '1',
      name: 'Vinos Tintos',
      slug: 'vinos-tintos',
      description: 'Vinos tintos',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    grapeIds: ['1'],
    grapes: [
      {
        id: '1',
        name: 'Tempranillo',
        description: 'Uva tinta española',
        color: 'tinto',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    wineType: 'tinto',
    vintage: 2020,
    volume: 750,
    alcohol: 14,
    acidity: 3.5,
    createdAt: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
  },
  {
    id: '9',
    name: 'Pazo de Señoans Albariño 2022',
    description: 'Albariño premium DO Rías Baixas',
    price: 16.99,
    image: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=400&h=600&fit=crop',
    sku: 'PAZO-ALB-2022',
    stock: 95,
    featured: true,
    bodegaId: '9',
    bodega: {
      id: '9',
      name: 'Pazo de Señoans',
      description: 'Bodega gallega de albariño',
      country: 'España',
      region: 'Rías Baixas',
      founded: 2001,
      image: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=400&h=600&fit=crop',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    regionId: '4',
    region: {
      id: '4',
      name: 'Rías Baixas',
      country: 'España',
      description: 'Región de vinos blancos en Galicia',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    categoryId: '2',
    category: {
      id: '2',
      name: 'Vinos Blancos',
      slug: 'vinos-blancos',
      description: 'Vinos blancos',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    grapeIds: ['3'],
    grapes: [
      {
        id: '3',
        name: 'Albariño',
        description: 'Uva blanca gallega',
        color: 'blanco',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    wineType: 'blanco',
    vintage: 2022,
    volume: 750,
    alcohol: 12.5,
    acidity: 3.4,
    ratings: [
      {
        id: '9',
        productId: '9',
        critic: 'Parker',
        score: 89,
        source: 'Robert Parker',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
  },
  {
    id: '10',
    name: 'Vermouth Carpano Antica Formula',
    description: 'Vermut italiano premium',
    price: 14.99,
    comparePrice: 18.99,
    image: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=400&h=600&fit=crop',
    sku: 'CARP-ANTIGA',
    stock: 70,
    featured: false,
    bodegaId: '10',
    bodega: {
      id: '10',
      name: 'Carpano',
      description: 'Casa italiana de vermut',
      country: 'Italia',
      region: 'Turín',
      founded: 1786,
      image: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=400&h=600&fit=crop',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    regionId: '8',
    region: {
      id: '8',
      name: 'Turín',
      country: 'Italia',
      description: 'Región de vermut italiano',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    categoryId: '6',
    category: {
      id: '6',
      name: 'Vermut',
      slug: 'vermut',
      description: 'Vermuts',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    grapeIds: ['11'],
    grapes: [
      {
        id: '11',
        name: 'Blend Especial',
        description: 'Blend de vermut',
        color: 'blanco',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    wineType: 'fortified',
    vintage: 2023,
    volume: 1000,
    alcohol: 16,
    acidity: 2.8,
    createdAt: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
  },
  {
    id: '11',
    name: 'La Rioja Alta Viña Ardanza 2017',
    description: 'Vino tinto reserva DO Rioja',
    price: 27.99,
    image: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=400&h=600&fit=crop',
    sku: 'LRA-ARDANZA-2017',
    stock: 55,
    featured: true,
    bodegaId: '11',
    bodega: {
      id: '11',
      name: 'La Rioja Alta',
      description: 'Bodega tradicional riojana',
      country: 'España',
      region: 'Rioja',
      founded: 1890,
      image: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=400&h=600&fit=crop',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    regionId: '2',
    region: {
      id: '2',
      name: 'Rioja',
      country: 'España',
      description: 'La región vitivinícola más famosa de España',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    categoryId: '1',
    category: {
      id: '1',
      name: 'Vinos Tintos',
      slug: 'vinos-tintos',
      description: 'Vinos tintos',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    grapeIds: ['1'],
    grapes: [
      {
        id: '1',
        name: 'Tempranillo',
        description: 'Uva tinta española',
        color: 'tinto',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    wineType: 'tinto',
    vintage: 2017,
    volume: 750,
    alcohol: 14.5,
    acidity: 3.6,
    ratings: [
      {
        id: '11',
        productId: '11',
        critic: 'Parker',
        score: 94,
        source: 'Robert Parker',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    createdAt: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
  },
  {
    id: '12',
    name: 'Prosecco Valdobbiadene DOCG Extra Dry',
    description: 'Prosecco italiano espumoso',
    price: 11.99,
    comparePrice: 15.99,
    image: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=400&h=600&fit=crop',
    sku: 'PROSC-ED',
    stock: 150,
    featured: false,
    bodegaId: '12',
    bodega: {
      id: '12',
      name: 'Valdobbiadene',
      description: 'Bodega de prosecco italiano',
      country: 'Italia',
      region: 'Véneto',
      founded: 1950,
      image: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=400&h=600&fit=crop',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    regionId: '9',
    region: {
      id: '9',
      name: 'Véneto',
      country: 'Italia',
      description: 'Región de prosecco en Italia',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    categoryId: '7',
    category: {
      id: '7',
      name: 'Prosecco',
      slug: 'prosecco',
      description: 'Proseccos italianos',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    grapeIds: ['12'],
    grapes: [
      {
        id: '12',
        name: 'Glera',
        description: 'Uva blanca italiana',
        color: 'blanco',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    wineType: 'espumoso',
    vintage: 2023,
    volume: 750,
    alcohol: 11,
    acidity: 3.2,
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
  },
];

export default function Home() {
  return (
    <main className="w-full bg-white">
      {/* Hero Slider */}
      <div className="px-4 sm:px-6 lg:px-8 py-6">
        <div className="max-w-7xl mx-auto">
          <HeroSlider />
        </div>
      </div>

      {/* Trust Badges */}
      <div className="px-4 sm:px-6 lg:px-8 py-6 bg-gray-50">
        <div className="max-w-7xl mx-auto">
          <TrustBadges className="mb-0" />
        </div>
      </div>

      {/* Category Icons */}
      <CategoryIcons />

      {/* Top Sales Tags */}
      <TopSales />

      {/* Best Sellers Carousel */}
      <BestSellers products={MOCK_PRODUCTS} />

      {/* Blog Preview */}
      <BlogPreview />

      {/* Info Banners */}
      <InfoBanners />

      {/* New Arrivals */}
      <NewArrivals products={MOCK_PRODUCTS} />

      {/* Offers Section */}
      <OffersSection products={MOCK_PRODUCTS} />

      {/* Recommendations */}
      <Recommendations products={MOCK_PRODUCTS} />

      {/* Referral Banner */}
      <ReferralBanner />

      {/* SEO Links */}
      <SeoLinks />
    </main>
  );
}
